// 비교 가이드 데이터 (ECC / PCE / Public) — PCE 기준
// 원천: config_master.json (EUG 203개 대조 + PCE 스크립트 56개 + 오마주 목차)
// Public "확인 중" 항목은 Public 매뉴얼 입수 후 보완 예정

const GUIDE_DATA = [
{
  id: "org-company", area: "조직구조", item: "회사 정의",
  ecc: "기업 구조 > 정의 > 재무회계 > 회사 정의",
  pce: "기업 구조 > 정의 > 재무회계",
  pub: "구현 액티비티(IMG) > 일반 설정 > 조직 구조 > 회사 > 회사 생성 (V_880_CLD)",
  diff: "최상위 조직 단위 정의. ECC·PCE 모두 IMG에서 직접 정의하며 개념은 동일. Public도 구현 액티비티(일반 설정 > 조직 구조 > 회사 > 회사 생성)에서 정의하며 개념은 동일하다.",
  help: [],
  tags: ["조직"], related: ["org-company-code", "org-ccode-company", "org-business-area"],
  eccSame: true
},
{
  id: "org-company-code", area: "조직구조", item: "회사코드 정의/복사/삭제",
  ecc: "기업 구조 > 정의 > 재무회계 > 회사코드 정의, 복사, 삭제, 점검",
  pce: "기업 구조 > 정의 > 재무회계",
  pub: "CBC (Central Business Configuration) > Set Up Organizational Structure (조직 구조 설정)",
  diff: "재무회계의 최소 독립 회계 단위. 정의·복사 체계는 ECC와 동일하나, S/4HANA에서는 회사코드 통화와 원장 통화의 연계가 병렬회계 설계와 직결되어 중요도가 상승.",
  help: [],
  tags: ["조직"], related: ["org-company", "org-ccode-company", "gl-global-param", "gl-fiscal-assign"],
  eccSame: true
},
{
  id: "org-ccode-company", area: "조직구조", item: "회사에 회사코드 지정",
  ecc: "기업 구조 > 지정 > 재무회계 > 회사에 회사코드 지정",
  pce: "기업 구조 > 지정 > 재무회계",
  pub: "구현 액티비티(IMG) > 일반 설정 > 조직 구조 > 회사 > 회사에 회사코드 지정 (SIMG_CFMENUSAPCOX16)",
  diff: "회사-회사코드 연결 관계 지정. ECC와 동일.",
  help: [],
  tags: ["조직"], related: ["org-company", "org-company-code", "co-ccassign"],
  eccSame: true
},
{
  id: "org-business-area", area: "조직구조", item: "사업영역 정의",
  ecc: "기업 구조 > 정의 > 재무회계 > 사업영역 정의",
  pce: "기업 구조 > 정의 > 재무회계",
  pub: "사용불가 (2608 버전 현재)",
  diff: "S/4HANA Public(2608 버전 현재)에서는 사업영역을 사용할 수 없다. 사업영역 대신 손익센터(Profit Center)로 구분하는 것을 권장한다.",
  help: ["https://userapps.support.sap.com/sap/support/knowledge/en/2760863"],
  tags: ["조직"], related: ["org-company-code", "co-prctr", "gl-docsplit"],
  eccSame: true
},
{
  id: "org-functional-area", area: "조직구조", item: "기능영역 정의",
  ecc: "기업 구조 > 정의 > 재무회계 > 기능영역 정의",
  pce: "기업 구조 > 정의 > 재무회계",
  pub: "CBC > Accounting > General Ledger > Reporting and Analytics for General Ledger > General Ledger Standard Reporting and Analytical Apps > Define Functional Area (102363)",
  diff: "매출원가 회계 활성화 시 기능영역 대체 설정이 필수(PCE CS-FI-0017 참조). 개념은 ECC와 동일.",
  help: [],
  tags: ["조직"], related: ["org-company-code", "gl-docsplit"],
  eccSame: true
},
{
  id: "org-fm-area", area: "조직구조", item: "재무관리영역 유지보수",
  flag: "FM 모듈 사용 시에만 적용 · FM 활성화 시에만 적용 가능",
  ecc: "기업 구조 > 정의 > 재무회계 > 재무관리영역 유지보수",
  pce: "기업 구조 > 정의 > 재무회계",
  pub: "확인 중",
  diff: "자금관리(FM) 조직 단위. ECC와 동일.",
  help: [],
  tags: ["조직"], related: ["org-company-code", "org-fm-ccode"],
  eccSame: true
},
{
  id: "org-fm-ccode", area: "조직구조", item: "재무관리영역에 회사코드 지정",
  flag: "FM 모듈 사용 시에만 적용 · FM 활성화 시에만 적용 가능",
  ecc: "기업 구조 > 지정 > 재무회계 > 재무관리영역에 회사코드 지정",
  pce: "기업 구조 > 지정 > 재무회계",
  pub: "확인 중",
  diff: "ECC와 동일.",
  help: [],
  tags: ["조직"], related: ["org-fm-area", "org-company-code"],
  eccSame: true
},
{
  id: "org-credit-area", area: "조직구조", item: "신용관리영역에 회사코드 지정",
  ecc: "기업 구조 > 지정 > 재무회계 > 신용관리영역에 회사코드 지정",
  pce: "기업 구조 > 지정 > 재무회계",
  pub: "확인 중",
  diff: "신용관리 조직 단위 지정. S/4HANA에서는 FSCM 신용관리로 기능이 이관되어 연계 확인이 필요.",
  help: [],
  tags: ["조직"], related: ["org-company-code", "ar-credit"],
  eccSame: false
},
{
  id: "gl-field-status", area: "G/L", item: "필드 상태 변형 정의",
  ecc: "재무회계 > 재무회계 기본세팅 > 원장 > 필드 > 필드상태변형 정의",
  pce: "재무회계 > 재무회계 전역 설정 > 원장 > 필드",
  pub: "CBC > Accounting > General Ledger > General Ledger Processes > General Journal Entries > Define Field Status Variants (102393)",
  diff: "전표 입력 화면의 필드 제어(필수/선택/숨김) 정의. ECC와 개념·설정 체계 동일.",
  help: [],
  tags: ["G/L", "전표"], related: ["gl-field-status-assign", "gl-acct-group", "gl-posting-key"],
  eccSame: true
},
{
  id: "gl-field-status-assign", area: "G/L", item: "회사코드를 필드상태변형에 지정",
  ecc: "재무회계 > 재무회계 기본세팅 > 원장 > 필드 > 회사코드를 필드상태변형에 지정",
  pce: "재무회계 > 재무회계 전역 설정 > 원장 > 필드",
  pub: "확인 중",
  diff: "ECC와 동일.",
  help: [],
  tags: ["G/L"], related: ["gl-field-status", "org-company-code"],
  eccSame: true
},
{
  id: "gl-ledger", area: "G/L", item: "원장 정의",
  ecc: "재무회계 > 재무회계 기본세팅 > 원장 > 원장 > 총계정원장 회계에 대한 원장 정의",
  pce: "재무회계 > 재무회계 전역 설정 > 원장 > 원장",
  pub: "확인 중",
  diff: "ECC New GL의 원장 개념은 유지되나, S/4HANA에서는 Universal Journal(ACDOCA) 단일 테이블이 실제 전기 원천. 원장은 회계기준별 병렬회계 용도로 정의.",
  help: ["https://help.sap.com/doc/0df2ffddebab40cf9338488b2f18dc41/2025.latest/en-US/SIMPL_OP2025.pdf"],
  tags: ["G/L", "전표"], related: ["gl-ledger-group", "gl-acct-principle", "gl-fiscal-year"],
  eccSame: false
},
{
  id: "gl-ledger-group", area: "G/L", item: "원장그룹 정의",
  ecc: "재무회계 > 재무회계 기본세팅 > 원장 > 원장 > 원장그룹 정의",
  pce: "재무회계 > 재무회계 전역 설정 > 원장 > 원장",
  pub: "SAP Business Configuration > 회계 > 총계정원장 > 원장 및 회계 원칙 > 보고를 위한 복수 원장 > 원장 그룹 정의",
  diff: "원장을 묶어 전기·조회하는 단위. ECC와 개념 동일.",
  help: [],
  tags: ["G/L", "전표"], related: ["gl-ledger", "gl-acct-principle"],
  eccSame: true
},
{
  id: "gl-acct-principle", area: "G/L", item: "회계기준 정의 및 원장그룹 지정",
  ecc: "재무회계 > 재무회계 기본세팅 > 원장 > 병렬회계 > 회계기준 정의 / 회계기준을 원장그룹에 지정",
  pce: "재무회계 > 재무회계 전역 설정 > 원장 > 병렬회계",
  pub: "CBC > Accounting > General Ledger > General Ledger Processes > Classic Foreign Currency Valuation > Assign Valuation Areas and Accounting Principles (101627)",
  diff: "S/4HANA에서는 감가상각영역이 원장(그룹)에 직접 매핑되어 병렬회계 설정이 New AA 설계와 직결됨.",
  help: ["https://help.sap.com/doc/0df2ffddebab40cf9338488b2f18dc41/2025.latest/en-US/SIMPL_OP2025.pdf"],
  tags: ["G/L"], related: ["gl-ledger", "gl-ledger-group"],
  eccSame: false
},
{
  id: "gl-fiscal-year", area: "G/L", item: "회계연도변형 유지보수",
  ecc: "재무회계 > 재무회계 기본세팅 > 원장 > 회계연도 및 전기 기간 > 회계연도변형 유지보수",
  pce: "재무회계 > 재무회계 전역 설정 > 원장 > 회계연도 및 전기기간",
  pub: "CBC > Accounting > General Ledger > Fiscal Year > Fiscal Year Variant used for All Company Codes > Maintain Fiscal Year Variants (102712)",
  diff: "ECC와 동일.",
  help: [],
  tags: ["G/L"], related: ["gl-fiscal-assign", "gl-pp-variant", "gl-posting-period"],
  eccSame: true
},
{
  id: "gl-fiscal-assign", area: "G/L", item: "회사코드를 회계연도변형에 지정",
  ecc: "재무회계 > 재무회계 기본세팅 > 원장 > 회계연도 및 전기 기간 > 회사코드를 회계연도변형에 지정",
  pce: "재무회계 > 재무회계 전역 설정 > 원장 > 회계연도 및 전기기간",
  pub: "SAP Business Configuration > 회계 > 총계정원장 > 회계연도 > 모든 회사 코드에 사용되는 회계연도 변형 > 원장 및 회사 코드에 회계연도 변형 지정",
  diff: "ECC와 동일.",
  help: [],
  tags: ["G/L"], related: ["gl-fiscal-year", "org-company-code", "gl-pp-variant"],
  eccSame: true
},
{
  id: "gl-pp-variant", area: "G/L", item: "개시 전기기간 변형 정의",
  ecc: "재무회계 > 재무회계 기본세팅 > 원장 > 회계연도 및 전기 기간 > 전기 기간 > 개시 전기기간에 대한 변형 정의",
  pce: "재무회계 > 재무회계 전역 설정 > 원장 > 전기 기간",
  pub: "CBC > Accounting > General Ledger > Fiscal Year > Financial Reports using Different Fiscal Year Variants > Define Variants for Open Posting Periods (101018)",
  diff: "ECC와 동일.",
  help: [],
  tags: ["G/L", "전표"], related: ["gl-posting-period", "gl-fiscal-year", "gl-doc-type"],
  eccSame: true
},
{
  id: "gl-posting-period", area: "G/L", item: "전기기간 개시 및 마감",
  ecc: "재무회계 > 재무회계 기본세팅 > 원장 > 회계연도 및 전기 기간 > 전기 기간 > 전기기간 개시 및 마감",
  pce: "재무회계 > 재무회계 전역 설정 > 원장 > 전기기간",
  pub: "Fiori 'Manage Posting Period' 앱 (Scope Item J58)",
  diff: "PCE에서는 OB52로 개시/마감하며 개념은 ECC와 동일. Public은 Fiori 앱으로 수행.",
  help: [],
  tags: ["G/L", "전표", "Fiori"], related: ["gl-pp-variant", "close-carryfwd", "gl-doc-type"],
  eccSame: true
},
{
  id: "gl-doc-type", area: "G/L", item: "전표유형 정의",
  ecc: "재무회계 > 재무회계 기본세팅 > 전표 > 전표유형 > 데이터 입력뷰의 전표유형 정의",
  pce: "재무회계 > 재무회계 전역 설정 > 전표 > 전표유형",
  pub: "CBC > Accounting > General Ledger > General Ledger Processes > General Journal Entries > Define Document Types (101522)",
  diff: "ECC와 개념 동일. Public은 SSCUI 500242에서 정의.",
  help: [],
  tags: ["G/L", "전표"], related: ["gl-doc-number", "gl-pp-variant", "gl-doc-change"],
  eccSame: true
},
{
  id: "gl-doc-number", area: "G/L", item: "전표 번호범위 정의",
  ecc: "재무회계 > 재무회계 기본세팅 > 전표 > 전표번호범위 > 데이터 입력뷰에 대한 전표 번호범위 정의",
  pce: "재무회계 > 재무회계 전역 설정 > 전표 > 전표유형",
  pub: "CBC > Accounting > General Ledger > General Ledger Processes > General Journal Entries > Define Document Number Ranges (101702)",
  diff: "ECC와 동일.",
  help: [],
  tags: ["G/L", "전표"], related: ["gl-doc-type"],
  eccSame: true
},
{
  id: "gl-posting-key", area: "G/L", item: "전기키 정의",
  ecc: "재무회계 > 재무회계 기본세팅 > 전표 > 전기키 정의",
  pce: "재무회계 > 재무회계 전역 설정 > 전표 > 전표 번호 범위",
  pub: "확인 중",
  diff: "차/대변, 계정유형별 전기 규칙 정의. ECC와 동일. (EUG 문서에는 별도 항목 없음)",
  help: [],
  tags: ["G/L", "전표"], related: ["gl-doc-type", "gl-field-status"],
  eccSame: true
},
{
  id: "gl-tolerance", area: "G/L", item: "종업원 허용한도그룹 정의",
  ecc: "재무회계 > 재무회계 기본세팅 > 전표 > 허용한도그룹 > 종업원에 대한 허용한도그룹 정의",
  pce: "재무회계 > 재무회계 전역 설정 > 전표 > 허용 한도 그룹",
  pub: "CBC > Payables and Receivables Management > Payment Processing > Business Partner-Initiated Payment and Clearing > Business-Partner-Initiated Payments > Define Tolerance Groups for Employees (102832)",
  diff: "전표 입력 금액 한도 그룹. ECC와 동일.",
  help: [],
  tags: ["G/L", "전표"], related: ["org-company-code", "gl-posting-key"],
  eccSame: true
},
{
  id: "gl-global-param", area: "G/L", item: "회사코드 광역매개변수",
  ecc: "재무회계 > 재무회계 기본세팅 > 회사 코드에 대한 전역 매개변수 > 광역매개변수 입력",
  pce: "재무회계 > 재무회계 전역 설정 > 회사 코드에 대한 전역 매개변수",
  pub: "확인 중",
  diff: "회사코드의 기본 통화·계정과목표·필드상태변형 등 전역 기본값. ECC와 동일.",
  help: [],
  tags: ["G/L"], related: ["org-company-code", "gl-field-status-assign"],
  eccSame: true
},
{
  id: "gl-doc-change", area: "G/L", item: "전표변경규칙",
  ecc: "재무회계 > 재무회계 기본세팅 > 전표 > 전표변경규칙 > 전표변경규칙, 전표헤더/개별항목",
  pce: "재무회계 > 재무회계 전역 설정 > 전표 > 전표 변경 규칙",
  pub: "SAP Business Configuration > 회계 > 총계정원장 > 총계정원장 프로세스 > 일반 분개 > 분개 변경 규칙 정의",
  diff: "전기 후 변경 가능 필드 규칙. ECC와 동일.",
  help: [],
  tags: ["G/L", "전표"], related: ["gl-doc-type"],
  eccSame: true
},
{
  id: "gl-coa", area: "G/L", item: "계정과목표 정의",
  ecc: "재무회계 > 총계정원장 회계 > 마스터 데이터 > G/L 계정 > 준비사항 > 계정과목표 리스트 편집",
  pce: "재무회계 > 총계정원장 회계 > 마스터 데이터 > G/L 계정 > 준비사항",
  pub: "SAP Business Configuration > 회계 > 총계정원장 > 계정과목표 > 계정과목표 및 재무제표 > 계정과목표 관리",
  diff: "ECC와 개념 동일. Public은 SSCUI 500043에서 계정과목표 관리.",
  help: [],
  tags: ["G/L"], related: ["gl-coa-assign", "gl-acct-group", "gl-retained"],
  eccSame: true
},
{
  id: "gl-coa-assign", area: "G/L", item: "회사코드를 계정과목표에 지정",
  ecc: "재무회계 > 총계정원장 회계 > 마스터 데이터 > G/L 계정 > 준비사항 > 회사코드를 계정과목표에 지정",
  pce: "재무회계 > 총계정원장 회계 > 마스터 데이터 > G/L 계정 > 준비사항",
  pub: "SAP Business Configuration > 회계 > 총계정원장 > 계정과목표 > 계정과목표 및 재무제표 > 회사코드를 계정과목표로 지정",
  diff: "ECC와 동일. (EUG 문서에는 별도 항목 없음)",
  help: [],
  tags: ["G/L"], related: ["gl-coa", "org-company-code"],
  eccSame: true
},
{
  id: "gl-acct-group", area: "G/L", item: "G/L 계정그룹 정의",
  ecc: "재무회계 > 총계정원장 회계 > 마스터 데이터 > G/L 계정 > 준비사항 > 계정그룹 정의",
  pce: "재무회계 > 총계정원장 회계 > 마스터 데이터 > G/L 계정 > 준비사항",
  pub: "SAP Business Configuration > 회계 > 총계정원장 > 계정과목표 > 계정과목표 및 재무제표 > 계정그룹정의",
  diff: "계정 마스터의 필드 제어·번호범위 그룹. ECC와 동일, Public은 Fiori 앱으로 마스터 관리.",
  help: [],
  tags: ["G/L", "마스터"], related: ["gl-coa", "gl-field-status"],
  eccSame: true
},
{
  id: "gl-retained", area: "G/L", item: "이익잉여금계정 정의",
  ecc: "재무회계 > 총계정원장 회계 > 마스터 데이터 > G/L 계정 > 준비사항 > 이익잉여금계정 정의",
  pce: "재무회계 > 총계정원장 회계 > 마스터 데이터 > G/L 계정 > 준비사항",
  pub: "확인 중",
  diff: "손익계정의 결산 이월 대상 계정 지정. ECC와 동일.",
  help: [],
  tags: ["G/L"], related: ["gl-coa", "gl-fsver"],
  eccSame: true
},
{
  id: "gl-fsver", area: "G/L", item: "재무제표버전 정의",
  ecc: "재무회계 > 총계정원장 회계 > 마스터 데이터 > G/L 계정 > 준비사항 > 재무제표버전 정의",
  pce: "재무회계 > 총계정원장 회계 > 마스터 데이터 > G/L 계정",
  pub: "CBC > Accounting > General Ledger > Chart of Accounts > Chart of Accounts & Financial Statements > Define Financial Statement Versions (102669)",
  diff: "ECC와 개념 동일. Public은 SSCUI 500043에서 정의, Fiori 'Balance Sheet/Income Statement' 앱(J58)으로 조회.",
  help: [],
  tags: ["G/L"], related: ["gl-coa", "gl-acct-group", "gl-retained"],
  eccSame: true
},
{
  id: "gl-docsplit", area: "G/L", item: "전표분할 설정",
  ecc: "재무회계 > 총계정원장 회계 > 비즈니스 트랜잭션 > 전표분할 > 전표분할 활성화/분류/제로잔액계정 정의",
  pce: "재무회계 > 총계정원장 회계 > 비즈니스 트랜잭션 > 전표 분할",
  pub: "CBC > Accounting > General Ledger > Reporting and Analytics for General Ledger > Financial Reports Based on Profit Centers > Define Document Splitting Characteristics for General Ledger Accounting (102322)",
  diff: "S/4HANA에서는 세그먼트 보고를 위해 전표분할이 사실상 필수 설정. 제로잔액 임시계정 정의가 선행되어야 함.",
  help: ["https://help.sap.com/doc/0df2ffddebab40cf9338488b2f18dc41/2025.latest/en-US/SIMPL_OP2025.pdf"],
  tags: ["G/L", "전표"], related: ["gl-doc-type", "org-business-area"],
  eccSame: false
},
{
  id: "gl-validation", area: "G/L", item: "회계전표 유효성 확인",
  ecc: "재무회계 > 재무회계 기본세팅 > 툴 > 유효성 확인 / 대체 > 회계전표에서 유효성 확인",
  pce: "재무회계 > 재무회계 전역 설정 > 툴 > 유효성 확인 / 대체",
  pub: "확인 중",
  diff: "전기 시 조건 체크 규칙. ECC와 동일.",
  help: [],
  tags: ["G/L", "전표"], related: ["gl-substitution", "gl-doc-type"],
  eccSame: true
},
{
  id: "gl-substitution", area: "G/L", item: "회계전표 대체",
  ecc: "재무회계 > 재무회계 기본세팅 > 툴 > 유효성 확인 / 대체 > 회계전표내 대체",
  pce: "재무회계 > 재무회계 전역 설정 > 툴 > 유효성 확인 / 대체",
  pub: "확인 중",
  diff: "전기 시 필드값 자동 대체 규칙. ECC와 동일.",
  help: [],
  tags: ["G/L", "전표"], related: ["gl-validation", "gl-doc-type"],
  eccSame: true
},
{
  id: "gl-clear-prep", area: "G/L", item: "자동반제 준비",
  ecc: "재무회계 > 총계정원장 회계 > 비즈니스 트랜잭션 > 미결 항목 반제 > 자동반제준비",
  pce: "재무회계 > 총계정원장 회계 > 비즈니스 트랜잭션 > 미결 항목 반제",
  pub: "CBC > Accounting > General Ledger > General Ledger Processes > Journal Entry Clearing > Prepare Automatic Clearing (101971)",
  diff: "자동반제 기준(반제규칙) 사전 준비. ECC와 동일.",
  help: [],
  tags: ["G/L", "전표"], related: ["close-autoclear"],
  eccSame: true
},
{
  id: "ap-bp-role", area: "AP", item: "BP 역할 활성화/정의",
  ecc: "해당 없음 (ECC에는 BP 개념 없음)",
  pce: "어플리케이션 전반 컴포넌트 > SAP 비즈니스 파트너",
  pub: "SSCUI 500092 (그룹핑·번호범위 중심, 역할 정의는 제한적)",
  diff: "ECC의 고객/공급처 마스터가 S/4HANA에서 비즈니스 파트너(BP)로 통합. 역할(Role)·역할범주·그룹핑 정의가 마스터 전략의 출발점.",
  help: [],
  tags: ["AP", "BP", "마스터"], related: ["ap-bp-num", "ap-cvi", "ap-vendor-group"],
  eccSame: false
},
{
  id: "ap-bp-num", area: "AP", item: "BP 번호범위 및 그룹핑",
  ecc: "해당 없음",
  pce: "어플리케이션 전반 컴포넌트 > SAP 비즈니스 파트너 > 비즈니스 파트너 > 기본설정 > 번호범위 및 그룹핑",
  pub: "SSCUI 500092 '번호 범위 정의'",
  diff: "BP 그룹핑별 내부/외부 번호범위 지정. Public은 SSCUI 500092에서 번호범위 정의 가능.",
  help: [],
  tags: ["AP", "BP"], related: ["ap-bp-role", "ap-vendor-num", "ap-cvi"],
  eccSame: false
},
{
  id: "ap-cvi", area: "AP", item: "CVI 통합 설정 (BP↔고객/공급처)",
  ecc: "해당 없음 (전환 프로젝트에서만 해당)",
  pce: "어플리케이션 전반 컴포넌트 > 마스터데이터동기화 > 고객/공급업체 통합 > 비즈니스파트너 설정",
  pub: "확인 중",
  diff: "S/4 전환 프로젝트의 필수 관문. BP와 고객/공급처 기술 마스터 간 번호·필드 동기화 방향을 정의.",
  help: ["https://community.sap.com/t5/enterprise-resource-planning-blog-posts-by-sap/faq-cvi-customer-vendor-integration-for-system-conversion-to-sap-s-4hana/ba-p/13740757"],
  tags: ["AP", "BP", "전환", "마스터"], related: ["ap-bp-role", "ap-vendor-group", "ar-cust-group", "ap-vendor-num"],
  eccSame: false
},
{
  id: "ap-vendor-group", area: "AP", item: "공급처 계정그룹/화면레이아웃",
  ecc: "재무회계 > 채권 및 채무 > 공급업체 계정 > 마스터데이터 > 공급업체 마스터 레코드 생성 준비 > 계정그룹을 화면레이아웃으로 정의",
  pce: "재무회계 > 채권 및 채무 > 공급업체 계정 > 마스터 데이터 > 공급업체 마스터 레코드 생성 준비",
  pub: "확인 중",
  diff: "계정그룹·번호범위 체계는 유지되나 마스터 입력 채널이 BP 트랜잭션으로 일원화됨.",
  help: [],
  tags: ["AP", "BP", "마스터"], related: ["ap-vendor-num", "ap-cvi", "ap-recon"],
  eccSame: false
},
{
  id: "ap-vendor-num", area: "AP", item: "공급처 번호범위",
  ecc: "재무회계 > 채권 및 채무 > 공급업체계정 > 마스터데이터 > 공급업체 마스터 레코드 생성 준비 > 구매처계정에 대한 번호범위 생성",
  pce: "재무회계 > 채권 및 채무 > 공급업체 계정 > 마스터 데이터 > 공급업체 마스터 레코드 생성 준비",
  pub: "확인 중",
  diff: "ECC와 동일.",
  help: [],
  tags: ["AP", "BP"], related: ["ap-vendor-group", "ap-bp-num"],
  eccSame: true
},
{
  id: "ap-payterms", area: "AP", item: "지급조건 유지보수",
  ecc: "재무회계 > 채권 및 채무 > 비즈니스 트랜잭션 > 수령 송장 / 대변 메모 > 지급조건 유지보수",
  pce: "재무회계 > 채권 및 채무 > 비즈니스 트랜잭션 > 지급조건",
  pub: "SSCUI 500137 '지급조건 유지보수'",
  diff: "ECC와 개념 동일. Public은 SSCUI 500137에서 유지보수.",
  help: [],
  tags: ["AP", "BP"], related: ["ap-bank-determ", "ap-paymethod-ccode"],
  eccSame: true
},
{
  id: "ap-housebank", area: "AP", item: "House Bank 정의",
  ecc: "재무회계 > 은행 회계 > 은행 계좌 > House Bank 정의",
  pce: "재무회계 > 은행 회계 > 은행 계좌 > House Bank 정의",
  pub: "Fiori 'Manage Banks'/'Manage Bank Accounts' 앱 (Scope Item BFA)",
  diff: "지급용 자사 은행 정의. ECC와 개념 동일, Public은 Fiori 앱으로 관리.",
  help: [],
  tags: ["AP", "BP", "Fiori"], related: ["ap-bank-determ", "bank-master", "bank-glstruct"],
  eccSame: true
},
{
  id: "ap-paymethod-country", area: "AP", item: "국가별 지급방법 설정",
  ecc: "재무회계 > 채권 및 채무 > 비즈니스 트랜잭션 > 아웃고잉 지급 > 자동 아웃고잉 지급 > 지급 방법/회사코드 설정",
  pce: "재무회계 > 채권 및 채무 > 비즈니스 트랜잭션 > 아웃고잉 지급 > 자동 아웃고잉 지급",
  pub: "CBC > Payables and Receivables Management > Payment Processing > Company-Initiated Payment and Clearing > You use automatic payments and payment media formats > Set Up Payment Methods for Each Country/Region for Payment Transactions (101972)",
  diff: "ECC와 로직 동일. Public은 SSCUI 500137에서 설정.",
  help: [],
  tags: ["AP", "BP"], related: ["ap-paymethod-ccode", "ap-bank-determ"],
  eccSame: true
},
{
  id: "ap-paymethod-ccode", area: "AP", item: "회사코드별 지급방법 설정",
  ecc: "재무회계 > 채권 및 채무 > 비즈니스 트랜잭션 > 아웃고잉 지급 > 자동 아웃고잉 지급 > 지급 방법/회사코드 설정",
  pce: "재무회계 > 채권 및 채무 > 비즈니스 트랜잭션 > 아웃고잉 지급 > 자동 아웃고잉 지급",
  pub: "CBC > Payables and Receivables Management > Payment Processing > Company-Initiated Payment and Clearing > You use automatic payments and payment media formats > Set Up Payment Methods per Company Code for Payment Transactions (101044)",
  diff: "ECC와 로직 동일. Public은 SSCUI 500012에서 설정.",
  help: [],
  tags: ["AP", "BP"], related: ["ap-paymethod-country", "ap-bank-determ", "ap-housebank"],
  eccSame: true
},
{
  id: "ap-bank-determ", area: "AP", item: "자동지급 은행결정",
  ecc: "재무회계 > 채권 및 채무 > 비즈니스 트랜잭션 > 아웃고잉 지급 > 자동 아웃고잉 지급 > 은행결정",
  pce: "재무회계 > 채권 및 채무 > 비즈니스 트랜잭션 > 아웃고잉 지급 > 자동 아웃고잉 지급 > 은행결정",
  pub: "CBC > Payables and Receivables Management > Payment Processing > Company-Initiated Payment and Clearing > You use automatic payments and payment media formats > Set Up Bank Determination for Payment Transactions (101045)",
  diff: "지급 프로그램의 순위·은행계좌·지급용 G/L계정 결정. ECC와 로직 동일.",
  help: [],
  tags: ["AP", "BP"], related: ["ap-housebank", "ap-paymethod-ccode", "bank-glstruct"],
  eccSame: true
},
{
  id: "ap-payblock", area: "AP", item: "지급보류사유 정의",
  ecc: "재무회계 > 채권 및 채무 > 비즈니스 트랜잭션 > 지급 > 지급 전역 세팅 > 지급 보류 사유 > 지급보류사유 정의",
  pce: "재무회계 > 채권 및 채무 > 비즈니스 트랜잭션 > 아웃고잉 지급 > 지급보류사유 정의",
  pub: "확인 중",
  diff: "ECC와 동일.",
  help: [],
  tags: ["AP", "BP"], related: ["ap-bank-determ"],
  eccSame: true
},
{
  id: "ap-recon", area: "AP", item: "공급처 대체조정계정",
  ecc: "재무회계 > 채권 및 채무 > 비즈니스 트랜잭션 > 대체 조정 계정로 전기 > 기타 특별 G/L 거래 > 구매처에 대한 대체조정계정 정의",
  pce: "재무회계 > 채권 및 채무 > 공급업체 계정",
  pub: "CBC > Accounting > General Ledger > Account Determination > Account Determination in General Ledger > Define Alternative Reconciliation Accounts (102631)",
  diff: "ECC와 개념 동일. Public은 SSCUI 500043에서 정의.",
  help: [],
  tags: ["AP", "BP"], related: ["ap-vendor-group", "xmod-obyc"],
  eccSame: true
},
{
  id: "ar-cust-group", area: "AR", item: "고객 계정그룹/화면레이아웃",
  ecc: "재무회계 > 채권 및 채무 > 고객계정 > 마스터데이터 > 고객 마스터 레코드 생성 준비 > 계정그룹을 화면레이아웃으로 정의",
  pce: "재무회계 > 채권 및 채무 > 고객 계정 > 마스터 데이터 > 고객마스터 레코드 생성 준비",
  pub: "확인 중",
  diff: "BP 일원화로 마스터 입력은 BP 트랜잭션, 고객 회계뷰는 역할로 부여. 계정그룹 체계는 유지.",
  help: [],
  tags: ["AR", "BP", "마스터"], related: ["ar-cust-num", "ap-cvi", "ar-recon"],
  eccSame: false
},
{
  id: "ar-cust-num", area: "AR", item: "고객 번호범위",
  ecc: "재무회계 > 채권 및 채무 > 고객계정 > 마스터데이터 > 고객 마스터 레코드 생성 준비 > 고객계정에 대한 번호범위 생성",
  pce: "재무회계 > 채권 및 채무 > 고객 계정 > 마스터 데이터 > 고객마스터 레코드 생성 준비",
  pub: "확인 중",
  diff: "ECC와 동일.",
  help: [],
  tags: ["AR", "BP"], related: ["ar-cust-group"],
  eccSame: true
},
{
  id: "ar-interest", area: "AR", item: "이자계산",
  flag: "국내 프로젝트 적용 드묾 · 상대가 이자를 안 줌",
  ecc: "재무회계 > 채권 및 채무 > 고객 계정 > 비즈니스 트랜잭션 > 이자계산",
  pce: "재무회계 > 채권 및 채무 > 고객 계정 > 비즈니스 트랜잭션 > 이자계산",
  pub: "SAP Business Configuration > 채무 및 채권 관리 > 미결 항목 관리 > 이자 계산",
  diff: "연체 이자 계산 유형·이자율 정의. ECC와 개념 동일.",
  help: [],
  tags: ["AR", "BP"], related: ["ar-dunning"],
  eccSame: true
},
{
  id: "ar-dunning", area: "AR", item: "독촉 절차",
  flag: "국내 프로젝트 적용 드묾 · Dunning보다 전화로 독촉함",
  ecc: "재무회계 > 채권 및 채무 > 고객 계정 > 비즈니스 트랜잭션 > 독촉",
  pce: "재무회계 > 채권 및 채무 > 고객 계정 > 비즈니스 트랜잭션 > 독촉",
  pub: "CBC > Payables and Receivables Management > Open Item Management > Dunning > Define your dunning procedures > Define Dunning Procedures (102302)",
  diff: "독촉 레벨·간격·문구 설정. 실행은 PCE에서 F150과 Fiori 앱 병행.",
  help: [],
  tags: ["AR", "BP"], related: ["ar-interest", "ar-cust-group"],
  eccSame: true
},
{
  id: "ar-credit", area: "AR", item: "신용관리",
  ecc: "재무회계 > 채권 및 채무 > 신용관리 (신용관리영역·신용한도)",
  pce: "재무회계 > 채권 및 채무 > 신용관리 (FSCM)",
  pub: "SAP Business Configuration > 채무 및 채권 관리 > 여신 관리",
  diff: "ECC의 신용관리는 S/4HANA에서 FSCM 신용관리로 이관. 신용한도·위험범주·체크 규칙 체계가 변경됨.",
  help: [],
  tags: ["AR", "BP"], related: ["org-credit-area", "ar-cust-group"],
  eccSame: false
},
{
  id: "ar-recon", area: "AR", item: "고객 대체조정계정",
  ecc: "재무회계 > 채권 및 채무 > 비즈니스 트랜잭션 > 대체 조정 계정로 전기 > 기타 특별 G/L 거래 > 고객에 대한 대체조정계정 정의",
  pce: "재무회계 > 채권 및 채무 > 고객 계정",
  pub: "CBC > Accounting > General Ledger > Account Determination > Account Determination in General Ledger > Define Alternative Reconciliation Accounts (102631)",
  diff: "ECC와 개념 동일. Public은 SSCUI 500043에서 정의.",
  help: [],
  tags: ["AR", "BP"], related: ["ar-cust-group", "ap-recon"],
  eccSame: true
},
{
  id: "ar-reason", area: "AR", item: "사유코드 정의",
  flag: "국내 프로젝트 적용 드묾 · 끝까지 추적함",
  ecc: "재무회계 > 채권 및 채무 > 고객 계정 > 비즈니스 트랜잭션 > 사유코드",
  pce: "재무회계 > 채권 및 채무 > 비즈니스 트랜잭션 > 사유코드",
  pub: "확인 중",
  diff: "지급차이·반제차이 사유코드. ECC와 동일.",
  help: [],
  tags: ["AR", "BP", "전표"], related: ["ar-overunder", "ar-cashdisc"],
  eccSame: true
},
{
  id: "ar-cashdisc", area: "AR", item: "현금할인/지급차이 처리",
  flag: "국내 프로젝트 적용 드묾 · 현금할인하면 세금계산서 재발행해야 함",
  ecc: "재무회계 > 채권 및 채무 > 고객 계정 > 비즈니스 트랜잭션 > 현금할인",
  pce: "재무회계 > 채권 및 채무 > 비즈니스 트랜잭션",
  pub: "확인 중",
  diff: "조기 지급 할인 조건과 허용차이 한도. ECC와 개념 동일.",
  help: [],
  tags: ["AR", "BP"], related: ["ar-overunder", "ar-reason"],
  eccSame: true
},
{
  id: "ar-overunder", area: "AR", item: "초과/미달지급 처리",
  flag: "국내 프로젝트 적용 드묾 · 끝까지 받아냄",
  ecc: "재무회계 > 채권 및 채무 > 고객 계정 > 비즈니스 트랜잭션 > 초과/미달 지급",
  pce: "재무회계 > 채권 및 채무 > 비즈니스 트랜잭션",
  pub: "확인 중",
  diff: "잔액 허용차이 내 자동 반제 규칙. ECC와 동일.",
  help: [],
  tags: ["AR", "BP", "전표"], related: ["ar-cashdisc", "ar-reason"],
  eccSame: true
},
{
  id: "ar-dispute", area: "AR", item: "분쟁관리 (FSCM)",
  flag: "별도 보관 (나중에 사용) · 별도 솔루션, 추가 조사 필요",
  ecc: "해당 없음 (ECC 분쟁관리는 별도 컴포넌트)",
  pce: "재무회계 > 채권 및 채무 > FSCM 분쟁관리",
  pub: "확인 중",
  diff: "S/4HANA에서는 FSCM 분쟁관리로 통합되어 사유코드·자동 케이스 생성 체계가 정비됨.",
  help: [],
  tags: ["AR", "BP"], related: ["ar-dunning", "ar-cust-group"],
  eccSame: false
},
{
  id: "bank-master", area: "은행", item: "은행마스터 정의",
  ecc: "재무회계 > 은행 회계 > 은행 마스터 데이터",
  pce: "재무회계 > 은행 회계 > 은행 마스터 데이터",
  pub: "Fiori 'Manage Banks' 앱 (Scope Item BFA)",
  diff: "은행 기본 마스터. Public은 Fiori 앱으로 관리.",
  help: [],
  tags: ["은행", "Fiori", "마스터"], related: ["bank-glstruct", "ap-housebank"],
  eccSame: true
},
{
  id: "bank-glstruct", area: "은행", item: "은행계좌 G/L 구조",
  ecc: "재무회계 > 은행 회계 > 은행 계좌 > 은행계좌 G/L 구조",
  pce: "재무회계 > 은행 회계 > 은행 계좌",
  pub: "확인 중",
  diff: "은행 하위계좌의 G/L 반영 구조. ECC와 동일.",
  help: [],
  tags: ["은행"], related: ["bank-master", "ap-housebank", "ap-bank-determ"],
  eccSame: true
},
{
  id: "bank-check", area: "은행", item: "수표번호 및 무효사유",
  flag: "최근 국내 프로젝트 적용 드묾 · 한국은 펌뱅킹·CMS 사용, 수표 잘 안 씀",
  ecc: "재무회계 > 은행 회계 > 지급수단 > 수표 로트/무효사유 정의",
  pce: "재무회계 > 은행 회계",
  pub: "확인 중",
  diff: "수표 발행 번호대와 무효 사유코드. ECC와 동일.",
  help: [],
  tags: ["은행"], related: ["ap-paymethod-country", "bank-master"],
  eccSame: true
},
{
  id: "aa-depchart", area: "자산회계", item: "참조감가상각표 복사",
  ecc: "재무회계 > 자산 회계 > 조직 구조 > 참조감가상각표/감가상각영역 복사",
  pce: "재무회계 > 자산 회계 > 조직 구조",
  pub: "SSCUI 500309 Configure Asset Accounting",
  diff: "S/4HANA에서는 감가상각영역이 원장에 직접 연결되므로 복사 후 영역-원장 매핑이 핵심.",
  help: [],
  tags: ["자산"], related: ["aa-depchart-assign", "aa-deparea"],
  eccSame: false
},
{
  id: "aa-depchart-assign", area: "자산회계", item: "감가상각표를 회사코드에 지정",
  ecc: "재무회계 > 자산 회계 > 조직 구조 > 감가상각표를 회사코드에 지정",
  pce: "재무회계 > 자산 회계 > 조직 구조",
  pub: "SSCUI 500309 Configure Asset Accounting",
  diff: "ECC와 동일.",
  help: [],
  tags: ["자산"], related: ["aa-depchart", "org-company-code", "aa-deparea"],
  eccSame: true
},
{
  id: "aa-deparea", area: "자산회계", item: "감가상각영역 정의",
  ecc: "재무회계 > 자산 회계 > 일반 평가 > 감가상각영역 정의",
  pce: "재무회계 > 자산 회계 > 일반 평가 > 감가상각 영역",
  pub: "SSCUI 500309 '회사 코드의 감가상각 영역 정의'",
  diff: "New AA에서는 감가상각영역이 원장 그룹에 매핑되어야 함. 실제 전기 영역과 통계 영역 구분이 중요.",
  help: [],
  tags: ["자산", "전표"], related: ["aa-depchart", "aa-acctdet"],
  eccSame: false
},
{
  id: "aa-class", area: "자산회계", item: "자산클래스 정의",
  ecc: "재무회계 > 자산 회계 > 자산 데이터 구조 > 자산클래스 정의",
  pce: "재무회계 > 자산 회계 > 자산 데이터 구조",
  pub: "CBC > Accounting > Asset Accounting > Fixed Assets > Asset Classes for Grouping of Fixed Assets > Define Asset Class (102606)",
  diff: "ECC와 개념 동일. Public은 SSCUI 500309에서 정의.",
  help: [],
  tags: ["자산"], related: ["aa-acctdet", "aa-numrange"],
  eccSame: true
},
{
  id: "aa-acctdet", area: "자산회계", item: "자산 계정결정",
  ecc: "재무회계 > 자산 회계 > 통합 > FI-GL과의 통합 > 계정결정 지정",
  pce: "재무회계 > 자산 회계 > 통합 > 계정결정 정의",
  pub: "CBC > Accounting > Asset Accounting > Fixed Assets > Account Determination in Fixed Assets > Assign G/L Accounts (102622)",
  diff: "ECC와 개념 동일. Public은 SSCUI 500309에서 정의.",
  help: [],
  tags: ["자산"], related: ["aa-class", "aa-deparea"],
  eccSame: true
},
{
  id: "aa-numrange", area: "자산회계", item: "자산 번호범위",
  ecc: "재무회계 > 자산 회계 > 조직 구조 > 번호범위간격 정의",
  pce: "재무회계 > 자산 회계 > 조직 구조",
  pub: "확인 중",
  diff: "ECC와 동일.",
  help: [],
  tags: ["자산"], related: ["aa-class"],
  eccSame: true
},
{
  id: "aa-depkey", area: "자산회계", item: "감가상각키",
  ecc: "재무회계 > 자산 회계 > 감가상각 > 평가방법 > 감가상각키 유지보수",
  pce: "재무회계 > 자산 회계 > 감가상각 > 평가방법",
  pub: "SSCUI 500309 (감가상각키·내용연수 설정)",
  diff: "ECC와 개념 동일.",
  help: [],
  tags: ["자산"], related: ["aa-deparea", "aa-class"],
  eccSame: true
},
{
  id: "aa-transtype", area: "자산회계", item: "자산 거래유형 정의",
  ecc: "재무회계 > 자산 회계 > 거래 > 취득/처분에 대한 거래유형 정의",
  pce: "재무회계 > 자산 회계 > 거래",
  pub: "확인 중",
  diff: "취득·처분·대체 거래유형. ECC와 동일.",
  help: [],
  tags: ["자산"], related: ["aa-class"],
  eccSame: true
},
{
  id: "aa-yearend", area: "자산회계", item: "자산 연마감/이월 (AJAB)",
  ecc: "AJRW (자산 연마감)",
  pce: "재무회계 > 자산 회계 > 정기 처리 > 연마감 (AJAB)",
  pub: "확인 중",
  diff: "New AA에서는 자산 연마감이 FI 연마감과 통합되어 AJAB로 일원화. ABST2(AA-FI 대사 리포트) 폐지.",
  help: ["https://help.sap.com/doc/0df2ffddebab40cf9338488b2f18dc41/2025.latest/en-US/SIMPL_OP2025.pdf"],
  tags: ["자산"], related: ["aa-transtype"],
  eccSame: false
},
{
  id: "tax-code", area: "세금", item: "세금코드 정의",
  ecc: "재무회계 > 재무회계 기본세팅 > 부가가치세 > 전기 > 세금코드 정의",
  pce: "재무회계 > 재무회계 전역 설정 > 세금 > 매출세/매입세 계산",
  pub: "SSCUI 500069 '세금코드 유지보수'",
  diff: "ECC와 개념 동일. Public은 SSCUI 500069에서 유지보수.",
  help: [],
  tags: ["세금"], related: ["tax-account", "tax-procedure", "tax-nontax"],
  eccSame: true
},
{
  id: "tax-account", area: "세금", item: "세금계정 정의",
  ecc: "재무회계 > 재무회계 기본세팅 > 부가가치세 > 전기 > 세금계정 정의",
  pce: "재무회계 > 재무회계 전역 설정 > 세금 > 매출세/매입세 계산",
  pub: "확인 중",
  diff: "세금 유형별 자동 전기 계정. ECC와 동일.",
  help: [],
  tags: ["세금", "전표"], related: ["tax-code"],
  eccSame: true
},
{
  id: "tax-procedure", area: "세금", item: "계산절차 점검 및 국가 지정",
  ecc: "재무회계 > 재무회계 기본세팅 > 부가가치세 > 전기 > 계산절차 점검 / 국가를 계산절차에 지정",
  pce: "재무회계 > 재무회계 전역 설정 > 세금 > 매출세/매입세 계산",
  pub: "CBC > Accounting > Tax Management > Tax on Goods and Services > tax Codes for Sales and Purchases > Assign Country/Region to Calculation Procedure (101721)",
  diff: "ECC와 동일.",
  help: [],
  tags: ["세금"], related: ["tax-code"],
  eccSame: true
},
{
  id: "tax-nontax", area: "세금", item: "비과세거래 세금코드",
  ecc: "재무회계 > 재무회계 기본세팅 > 부가가치세 > 전기 > 비과세 거래에 대한 세금코드 정의",
  pce: "재무회계 > 재무회계 전역 설정 > 세금 > 매출세/매입세 계산",
  pub: "CBC > Accounting > Tax Management > Tax on Goods and Services > Tax Codes for Sales and Purchases > Assign Tax Codes for Non-Taxable Transactions (102602)",
  diff: "ECC와 개념 동일. Public은 SSCUI 500069에서 지정.",
  help: [],
  tags: ["세금"], related: ["tax-code"],
  eccSame: true
},
{
  id: "wth-type", area: "세금", item: "원천세유형/코드 정의",
  ecc: "재무회계 > 재무회계 기본세팅 > 원천세 > 확장된 원천세 > 원천세키/코드 정의",
  pce: "재무회계 > 재무회계 전역 설정 > 원천세 > 확장된 원천세",
  pub: "SSCUI 500351 '원천세코드정의', '원천세유형을 회사코드에 지정'",
  diff: "ECC와 개념 동일. Public은 SSCUI 500351에서 정의.",
  help: [],
  tags: ["세금"], related: ["wth-account", "wth-section"],
  eccSame: true
},
{
  id: "wth-section", area: "세금", item: "섹션코드/사업장 정의",
  ecc: "재무회계 > 재무회계 기본세팅 > 원천세 > 사업장/섹션코드 정의",
  pce: "재무회계 > 재무회계 전역 설정 > 원천세",
  pub: "CBC > Compliance, Trade, and Quality > Legal Compliance > Business Place > Define Business Place for South Korea (104040)",
  diff: "원천세 신고 단위(사업장) 정의. ECC와 개념 동일.",
  help: [],
  tags: ["세금"], related: ["wth-type", "wth-account"],
  eccSame: true
},
{
  id: "co-area", area: "CO", item: "관리영역 정의",
  ecc: "관리회계 > 관리회계 기본 설정 > 조직 > 관리영역 유지보수",
  pce: "관리회계 > 관리회계 기본 설정 > 조직 > 관리영역 유지보수",
  pub: "확인 중",
  diff: "관리회계 최상위 조직. 회사코드 1:N 구조는 ECC와 동일하나, 원가요소-G/L계정 통합으로 계정체계 설계가 선행되어야 함.",
  help: [],
  tags: ["CO"], related: ["co-ccassign", "co-version", "org-company-code", "co-ml"],
  eccSame: false
},
{
  id: "co-ccassign", area: "CO", item: "회사코드를 관리영역에 지정",
  ecc: "관리회계 > 관리회계 기본 설정 > 조직 > 회사코드를 관리영역에 지정",
  pce: "관리회계 > 관리회계 기본 설정 > 조직",
  pub: "확인 중",
  diff: "ECC와 동일.",
  help: [],
  tags: ["CO"], related: ["co-area", "org-company-code", "org-ccode-company"],
  eccSame: true
},
{
  id: "co-celem", area: "CO", item: "원가요소 범주 (G/L계정 통합)",
  ecc: "관리회계 > 원가요소 회계 > 원가요소 마스터 데이터 > 1차/2차 원가요소 생성",
  pce: "관리회계 > 원가요소 회계 > 원가요소 마스터 데이터",
  pub: "확인 중",
  diff: "S/4HANA에서는 원가요소 마스터가 G/L계정 마스터와 통합. 1차 원가요소는 G/L계정 생성 시 자동 생성되며 별도 생성이 불필요.",
  help: ["https://help.sap.com/doc/0df2ffddebab40cf9338488b2f18dc41/2025.latest/en-US/SIMPL_OP2025.pdf"],
  tags: ["CO", "마스터"], related: ["co-area", "co-okb9", "co-ccenter", "co-payroll"],
  eccSame: false
},
{
  id: "co-ccenter", area: "CO", item: "코스트센터/표준계층",
  ecc: "관리회계 > 코스트센터 회계 > 마스터 데이터 > 코스트센터/표준계층",
  pce: "관리회계 > 코스트센터 회계 > 마스터 데이터",
  pub: "IMG 표시 > 회계 > 간접비 > 간접비 마스터 데이터 > 코스트 센터 > 코스트센터범주 정의",
  diff: "ECC와 개념 동일.",
  help: [],
  tags: ["CO"], related: ["co-area", "co-acttype", "co-skf", "co-alloc"],
  eccSame: true
},
{
  id: "co-acttype", area: "CO", item: "활동유형",
  ecc: "관리회계 > 코스트센터 회계 > 마스터 데이터 > 활동유형",
  pce: "관리회계 > 코스트센터 회계 > 마스터 데이터",
  pub: "확인 중",
  diff: "ECC와 개념 동일.",
  help: [],
  tags: ["CO"], related: ["co-ccenter", "co-area", "co-alloc"],
  eccSame: true
},
{
  id: "co-order", area: "CO", item: "내부오더 유형",
  ecc: "관리회계 > 내부오더 > 오더 마스터 데이터 > 오더 유형 정의",
  pce: "관리회계 > 내부오더 > 오더 마스터 데이터",
  pub: "확인 중",
  diff: "내부오더 유형·상태관리·예산. ECC와 개념 동일.",
  help: [],
  tags: ["CO"], related: ["co-settle", "co-area", "co-order-budget", "co-auc-settle"],
  eccSame: true
},
{
  id: "co-settle", area: "CO", item: "정산 프로파일/배분구조",
  ecc: "관리회계 > 내부오더 > 실제전기 > 정산 > 정산 프로파일/배분구조 정의",
  pce: "관리회계 > 내부오더 > 실제전기 > 정산",
  pub: "IMG 표시 > 회계 > 간접비 > 간접비 프로세스 > 기결산 > 정산 프로파일 생성",
  diff: "오더·프로젝트 정산 규칙. ECC와 개념 동일.",
  help: [],
  tags: ["CO"], related: ["co-order", "co-area", "co-auc-settle", "co-close"],
  eccSame: true
},
{
  id: "co-opcon", area: "CO", item: "경영단위 정의",
  ecc: "관리회계 > 수익성 분석 > 구조 > 경영단위 유지보수",
  pce: "관리회계 > 수익성 분석 > 구조",
  pub: "확인 중",
  diff: "ECC와 개념 동일.",
  help: [],
  tags: ["CO"], related: ["co-area", "xmod-copamap", "co-margin", "co-sd-copa"],
  eccSame: true
},
{
  id: "co-prctr", area: "CO", item: "손익센터 정의",
  ecc: "관리회계 > 손익센터 회계 > 마스터 데이터 > 손익센터",
  pce: "관리회계 > 손익센터 회계 > 마스터 데이터",
  pub: "CBC > Accounting > General Ledger > General Ledger Processes > General Ledger Processes > Assign Default Profit Center to Accounts (102529)",
  diff: "전표분할과 연계되는 손익센터. S/4HANA에서는 전표분할 활성화 시 손익센터 파생이 필수.",
  help: [],
  tags: ["CO", "전표"], related: ["co-area", "org-business-area", "co-margin", "gl-docsplit"],
  eccSame: false
},
{
  id: "co-version", area: "CO", item: "CO 버전 유지보수",
  ecc: "관리회계 > 관리회계 기본 설정 > 버전 유지보수",
  pce: "관리회계 > 관리회계 기본 설정 > 버전",
  pub: "확인 중",
  diff: "계획 버전 관리. ECC와 동일.",
  help: [],
  tags: ["CO"], related: ["co-area", "co-order-budget"],
  eccSame: true
},
{
  id: "close-cockpit", area: "결산", item: "결산콕핏",
  ecc: "재무회계 > 총계정원장 회계 > 정기 처리 > 결산콕핏 (작업 템플릿·태스크 정의)",
  pce: "재무회계 > 총계정원장 회계 > 정기 처리 > 결산콕핏",
  pub: "확인 중",
  diff: "S/4HANA 결산콕핏은 Fiori 기반 스케줄링·모니터링으로 고도화. 작업 템플릿·의존성 정의 체계는 ECC와 유사.",
  help: ["https://blog.sap-press.com/key-changes-to-period-end-closing-in-s/4hana-finance"],
  tags: ["결산"], related: ["close-jobs"],
  eccSame: false
},
{
  id: "close-fxval", area: "결산", item: "외화평가",
  ecc: "재무회계 > 총계정원장 회계 > 정기처리 > 평가 > 외화평가 > 외화평가에 대한 자동전기 준비",
  pce: "재무회계 > 총계정원장 회계 > 정기 처리 > 평가",
  pub: "SAP Business Configuration > 회계 > 총계정원장 > 총계정원장 프로세스 > 기존 외화 평가",
  diff: "평가방법·평가영역 정의 후 자동전기. 로직은 ECC와 동일.",
  help: [],
  tags: ["결산", "전표"], related: ["gl-fx-diff-acct"],
  eccSame: true
},
{
  id: "close-carryfwd", area: "결산", item: "잔액이월",
  ecc: "FAGLGVTR (G/L), AJRW (자산)",
  pce: "재무회계 > 총계정원장 회계 > 정기 처리 > 이월 (FAGLGVTR)",
  pub: "확인 중",
  diff: "New AA에서는 자산 잔액이월이 FI 이월과 통합되어 별도 자산 이월이 불필요.",
  help: [],
  tags: ["결산"], related: ["gl-posting-period"],
  eccSame: false
},
{
  id: "close-accrual", area: "결산", item: "발생엔진 (Accrual Engine)",
  ecc: "재무회계 > 총계정원장 회계 > 정기처리 > 기간손익/발생엔진 설정",
  pce: "재무회계 > 총계정원장 회계 > 정기 처리 > 발생엔진",
  pub: "확인 중",
  diff: "발생유형·평가영역·규칙세트 정의 체계는 ECC와 동일. S/4HANA에서는 구매오더 발생액 Fiori 앱(2VB)과 연계.",
  help: [],
  tags: ["결산"], related: ["close-cockpit"],
  eccSame: true
},
{
  id: "close-autoclear", area: "결산", item: "자동반제 실행",
  ecc: "F.13 (반제규칙 OBIA/OBIB)",
  pce: "F.13 유지",
  pub: "확인 중",
  diff: "로직은 유지, 실행 채널이 Fiori로 이동 중.",
  help: [],
  tags: ["결산", "전표"], related: ["gl-clear-prep", "close-grir"],
  eccSame: true
},
{
  id: "close-recurr", area: "결산", item: "정기/반복전표",
  ecc: "재무회계 > 총계정원장 회계 > 비즈니스 트랜잭션 > 정기전표",
  pce: "Fiori 'Manage Recurring Journal Entries' 앱",
  pub: "Fiori 'Manage Recurring Journal Entries' 앱 (Scope Item J58)",
  diff: "PCE에서는 GUI와 Fiori 병행, Public은 Fiori 앱 중심.",
  help: [],
  tags: ["결산", "전표", "Fiori"], related: ["gl-doc-type"],
  eccSame: true
},
{
  id: "close-grir", area: "결산", item: "GR/IR 미결관리",
  ecc: "F.13/MR11 (반제·잔액조정)",
  pce: "Fiori 'Reconcile GR/IR Accounts' 앱",
  pub: "Fiori 'Reconcile GR/IR Accounts' 앱 (Scope Item 2VB)",
  diff: "반제 로직은 유지되나 S/4HANA에서 Fiori 앱(2VB)으로 모니터링이 강화됨.",
  help: [],
  tags: ["결산", "전표", "Fiori"], related: ["xmod-griradj", "close-autoclear"],
  eccSame: false
},
{
  id: "xmod-obyc", area: "타모듈 연결", item: "MM-FI 자동계정결정 (OBYC)",
  ecc: "자재관리 > 평가 및 계정지정 > 계정결정 > 계정결정 마법사",
  pce: "자재관리 > 평가 및 계정지정 > 계정결정 > 계정결정 마법사",
  pub: "SAP Business Configuration > 회계 > 총계정원장 > 계정 결정 > 총계정원장의 계정 결정 > 자동 계정 결정",
  diff: "BSX(재고전기)·WRX(GR/IR)·PRD(가격차이) 등 이벤트키별 계정결정이 핵심. 평가클래스-이동유형 조합 체계는 ECC와 동일.",
  help: [],
  tags: ["연계", "전표"], related: ["xmod-griradj", "ap-recon"],
  eccSame: true
},
{
  id: "xmod-plant", area: "타모듈 연결", item: "플랜트를 회사코드에 지정",
  ecc: "기업 구조 > 지정 > 자재관리 > 플랜트를 회사코드에 지정",
  pce: "기업 구조 > 지정 > 자재관리",
  pub: "확인 중",
  diff: "MM-FI 연결의 출발점. ECC와 동일.",
  help: [],
  tags: ["연계"], related: ["org-company-code"],
  eccSame: true
},
{
  id: "xmod-ml", area: "타모듈 연결", item: "자재원장 활성화",
  ecc: "선택 사항 (관리회계 > 실제원가계산/자재원장)",
  pce: "관리회계 > 실제원가계산/자재원장 > 자재원장 활성화",
  pub: "확인 중",
  diff: "S/4HANA에서는 모든 플랜트에 자재원장 활성화가 필수. MLDOC·MLDOCCCS 테이블로 평가하며 Universal Journal과 통합.",
  help: ["https://blog.sap-press.com/the-material-ledger-and-actual-costing-with-sap-s4hana"],
  tags: ["연계", "자재원장"], related: ["xmod-obyc"],
  eccSame: false
},
{
  id: "xmod-vkoa", area: "타모듈 연결", item: "SD 수익계정결정 (VKOA)",
  ecc: "영업 및 유통 > 기본 기능 > 계정지정/원가계산 > 수익 계정 결정",
  pce: "영업 및 유통 > 기본 기능 > 계정지정/원가계산 > 수익 계정 결정",
  pub: "확인 중",
  diff: "조건유형·계정키(ERL/ERS) 기반 G/L계정 결정. S/4HANA에서도 VKOA 체계 유지.",
  help: [],
  tags: ["연계"], related: ["xmod-sdbill"],
  eccSame: true
},
{
  id: "xmod-copamap", area: "타모듈 연결", item: "SD 조건유형→CO-PA 값필드 매핑",
  ecc: "관리회계 > 수익성 분석 > 플로우 > 실제값 > SD 조건유형/계정키 지정",
  pce: "관리회계 > 수익성 분석 > 플로우",
  pub: "확인 중",
  diff: "SD 청구 조건이 CO-PA 값필드로 흐르는 인터페이스 정의. ECC와 개념 동일.",
  help: [],
  tags: ["연계"], related: ["co-opcon", "xmod-vkoa"],
  eccSame: true
},
{
  id: "xmod-payroll", area: "타모듈 연결", item: "급여전기 (HR→FI)",
  flag: "별도 보관 · 별도 e-HR 솔루션 사용이 많음",
  ecc: "인적자원관리 > 급여 > 평가 > 회계로의 전기",
  pce: "인적자원관리 > 급여관리 > 회계로의 전기",
  pub: "확인 중",
  diff: "급여전기 결과의 FI 전표 생성 규칙. ECC와 개념 동일.",
  help: [],
  tags: ["연계", "전표"], related: ["gl-doc-type"],
  eccSame: true
},
{
  id: "xmod-assetpo", area: "타모듈 연결", item: "자산구매오더 계정지정범주",
  ecc: "재무회계 > 자산 회계 > ... > 자산구매오더에 대한 계정지정범주 정의",
  pce: "재무회계 > 자산 회계 > 통합",
  pub: "확인 중",
  diff: "자산 구매오더의 계정지정 유형(A). ECC와 동일.",
  help: [],
  tags: ["연계"], related: ["aa-acctdet", "aa-class"],
  eccSame: true
},
{
  id: "xmod-sdbill", area: "타모듈 연결", item: "SD 인도·청구와 FI 전기 연계",
  ecc: "영업 및 유통 > 청구 > 청구문서 > 회계전기 연계",
  pce: "영업 및 유통 > 청구",
  pub: "확인 중",
  diff: "청구 문서 유형별 FI 전표 생성과 계정결정(VKOA) 연계. ECC와 개념 동일.",
  help: [],
  tags: ["연계", "전표"], related: ["xmod-vkoa", "gl-doc-type"],
  eccSame: true
},
{
  id: "xmod-griradj", area: "타모듈 연결", item: "GR/IR 반제 수정계정",
  ecc: "재무회계 > 총계정원장 회계 > 정기처리 > 재분류 > GRIR 반제에 대한 수정계정 정의",
  pce: "재무회계 > 총계정원장 회계 > 비즈니스 트랜잭션 > 미결 항목 반제",
  pub: "확인 중",
  diff: "GR/IR 반제 시 차이 조정용 수정계정. ECC와 동일.",
  help: [],
  tags: ["연계", "전표"], related: ["xmod-obyc", "close-grir"],
  eccSame: true
},
{
  id: "xmod-interco", area: "타모듈 연결", item: "회사간 전기 자동계정결정",
  ecc: "재무회계 > 재무회계 기본세팅 > 전표 > 회사간 전기 자동계정결정",
  pce: "재무회계 > 재무회계 전역 설정",
  pub: "확인 중",
  diff: "회사간 거래의 자동 상계계정 결정. ECC와 동일.",
  help: [],
  tags: ["연계", "전표"], related: ["org-company-code"],
  eccSame: true
},
{
  id: "gl-negative-posting", area: "G/L", item: "음의전기 허용",
  ecc: "재무회계 > 총계정원장 회계 > 비즈니스 트랜잭션 > 조정 전기 / 역분개 > 음의전기허용",
  pce: "재무회계 > 총계정원장 회계 > 비즈니스 트랜잭션 > 조정 전기/역분개",
  pub: "확인 중",
  diff: "회사코드별 음의전기 허용 여부. ECC와 동일.",
  help: [],
  tags: ["G/L", "전표"], related: ["gl-doc-type", "gl-reversal-reason"],
  eccSame: true
},
{
  id: "gl-reversal-reason", area: "G/L", item: "역분개사유 정의",
  ecc: "재무회계 > 총계정원장 회계 > 비즈니스 트랜잭션 > 조정 전기 / 역분개 > 역분개사유 정의",
  pce: "재무회계 > 총계정원장 회계 > 비즈니스 트랜잭션 > 조정 전기/역분개",
  pub: "CBC > Accounting > General Ledger > General Ledger Processes > General Journal Entries > Define Reasons for Reversal (101039)",
  diff: "역분개 시 사유코드와 전기일 규칙. ECC와 동일.",
  help: [],
  tags: ["G/L", "전표"], related: ["gl-doc-type", "gl-negative-posting"],
  eccSame: true
},
{
  id: "gl-fx-diff-acct", area: "G/L", item: "환율차이 계정 정의",
  ecc: "재무회계 > 총계정원장 회계 > 비즈니스 트랜잭션 > 미결 항목 반제 > 환율차이에 대한 계정 정의",
  pce: "재무회계 > 총계정원장 회계 > 비즈니스 트랜잭션 > 미결 항목 반제",
  pub: "확인 중",
  diff: "외화 반제 시 환율차이 자동 전기 계정. 외화평가 설정과 함께 확인. ECC와 동일.",
  help: [],
  tags: ["G/L", "전표"], related: ["close-fxval"],
  eccSame: true
},
{
  id: "aa-settlement", area: "자산회계", item: "자산 정산프로파일 정의",
  ecc: "재무회계 > 자산회계 > 거래 > 건설가계정 자본화 > 정산프로파일 정의 / 지정",
  pce: "재무회계 > 자산 회계 > 거래 > 건설가계정",
  pub: "확인 중",
  diff: "건설가계정(AuC) 정산 규칙. AA-CO 연계의 핵심으로 ECC와 개념 동일.",
  help: [],
  tags: ["자산"], related: ["aa-class", "co-settle"],
  eccSame: true
},
{
  id: "wth-account", area: "세금", item: "지급 원천세 계정 정의",
  ecc: "재무회계 > 재무회계 기본세팅 > 원천세 > 확장된 원천세 > 전기 > 원천세 계정 > 지급될 원천세에 대한 계정정의",
  pce: "재무회계 > 재무회계 전역 설정 > 원천세 > 확장된 원천세",
  pub: "확인 중",
  diff: "원천세 유형별 납부 계정 결정. ECC와 동일.",
  help: [],
  tags: ["세금"], related: ["wth-type"],
  eccSame: true
},
{
  id: "co-alloc", area: "CO", item: "배부/분배 사이클 정의",
  ecc: "관리회계 > 코스트센터 회계 > 기말결산 > 실제전기 > 배부/분배",
  pce: "관리회계 > 코스트센터 회계 > 기말결산",
  pub: "IMG 표시 > 회계 > 간접비 > 간접비 프로세스 > 기결산 > 배부 구조 유지보수",
  diff: "코스트센터에 모인 간접비를 배부기준(통계지표 등)으로 나누는 기말 작업. ECC와 개념은 동일하나, S/4HANA에서는 유니버설 배부(Universal Allocation)로 통합되는 추세.",
  help: [],
  tags: ["CO"], related: ["co-ccenter", "co-skf", "co-repost", "close-jobs"],
  eccSame: true
},
{
  id: "co-okb9", area: "CO", item: "OKB9 자동계정결정 (CO 오브젝트)",
  ecc: "재무회계 > 총계정원장 > 자동계정결정 > OKB9 (CO 오브젝트 기본값)",
  pce: "재무회계 > 총계정원장 > 자동계정결정",
  pub: "확인 중",
  diff: "외화평가·GR/IR 등 FI 자동전기 시 코스트센터 같은 CO 오브젝트가 필수인 경우 기본값을 지정하는 설정. FI-CO 연계의 실무 핵심 포인트.",
  help: [],
  tags: ["CO", "전표"], related: ["co-ccenter", "co-celem", "xmod-obyc", "close-fxval"],
  eccSame: true
},
{
  id: "co-margin", area: "CO", item: "마진분석 (계정기반 수익성분석)",
  ecc: "관리회계 > 수익성 분석 > 경영단위 (계정기반)",
  pce: "관리회계 > 수익성 분석",
  pub: "IMG 표시 > 회계 > 마진 분석 > 마진 분석 프로세스 > 하향식 분배 > 하향식 배부 템플릿 정의",
  diff: "S/4HANA의 표준 수익성분석. Costing-based COPA와 달리 별도 값필드 없이 G/L계정 기준으로 분석한다. Public에서는 Costing-based를 쓸 수 없어 마진분석이 필수.",
  help: [],
  tags: ["CO"], related: ["co-opcon", "co-sd-copa", "co-prctr", "xmod-vkoa"],
  eccSame: true
},
{
  id: "co-ml", area: "CO", item: "자재원장 활성화/실제원가계산",
  ecc: "관리회계 > 자재원장 > 자재원장 활성화",
  pce: "관리회계 > 자재원장",
  pub: "IMG 표시 > 회계 > 재고 회계 > 평가 방법 > 실제 원가계산 > 자재원장의 이동유형그룹 지정",
  diff: "자재의 실제원가를 주기 단위로 계산하는 FI-MM-CO 3자 연계 영역. S/4HANA에서는 자재원장이 필수 요소이며 실제원가계산으로 다자재·다통화 평가가 가능.",
  help: [],
  tags: ["CO", "자재원장"], related: ["co-costvar", "xmod-obyc", "co-close", "co-area"],
  eccSame: true
},
{
  id: "co-skf", area: "CO", item: "통계지표 정의",
  ecc: "관리회계 > 코스트센터 회계 > 마스터 데이터 > 통계지표",
  pce: "관리회계 > 코스트센터 회계 > 마스터 데이터",
  pub: "확인 중",
  diff: "인원수·면적 등 배부기준이 되는 마스터 데이터. 배부/분배 사이클에서 간접비를 나누는 기준으로 사용한다.",
  help: [],
  tags: ["CO", "마스터"], related: ["co-ccenter", "co-alloc", "co-acttype"],
  eccSame: true
},
{
  id: "co-repost", area: "CO", item: "정기 재전기",
  ecc: "관리회계 > 코스트센터 회계 > 기말결산 > 실제전기 > 정기 재전기",
  pce: "관리회계 > 코스트센터 회계 > 기말결산",
  pub: "확인 중",
  diff: "코스트센터에 잘못 집계된 비용을 다른 코스트센터로 옮기는 기말 조정 작업. 원전표는 그대로 두고 CO 내에서만 재분류한다.",
  help: [],
  tags: ["CO", "전표"], related: ["co-ccenter", "co-alloc", "close-jobs"],
  eccSame: true
},
{
  id: "co-order-budget", area: "CO", item: "내부오더 예산관리",
  ecc: "관리회계 > 내부오더 > 예산 > 예산관리",
  pce: "관리회계 > 내부오더",
  pub: "IMG 표시 > 회계 > 재무 계획 > 예산 편성 및 가용성 관리",
  diff: "내부오더별 예산 편성과 통제. 가용성 체크와 연계되어 예산 초과 전기를 막는 실무 필수 기능.",
  help: [],
  tags: ["CO", "전표"], related: ["co-order", "co-settle", "co-version"],
  eccSame: true
},
{
  id: "co-costvar", area: "CO", item: "원가계산 변형",
  ecc: "관리회계 > 제품원가 관리 > 원가계산 > 원가계산 변형 정의",
  pce: "관리회계 > 제품원가 관리",
  pub: "IMG 표시 > 회계 > 재고 회계 > 비즈니스 역할 템플릿 재고 회계 > 원가계산 변형 정의",
  diff: "제조원가 계산의 뼈대(평가전략·수량구조·부가가치 등)를 정하는 설정. CO-PC(제품원가관리) 영역의 출발점.",
  help: [],
  tags: ["CO"], related: ["co-ml", "co-area", "xmod-obyc"],
  eccSame: true
},
{
  id: "co-sd-copa", area: "CO", item: "SD 조건유형 → COPA 값필드 매핑",
  ecc: "관리회계 > 수익성 분석 > 플로우 > SD 인터페이스 > 조건유형을 값필드에 매핑",
  pce: "관리회계 > 수익성 분석 > SD 인터페이스",
  pub: "확인 중",
  diff: "SD 청구 시 수익성분석으로 넘기는 값의 연결고리. FI/CO 컨설턴트가 꼭 알아야 하는 SD 연계 포인트.",
  help: [],
  tags: ["CO"], related: ["co-opcon", "co-margin", "xmod-vkoa", "xmod-copamap"],
  eccSame: true
},
{
  id: "co-payroll", area: "CO", item: "급여전기 (HR→FI/CO 연계)",
  flag: "별도 보관 · 별도 e-HR 솔루션 사용이 많음",
  ecc: "인사관리 > 급여 > FI/CO 전기 (HR 모듈 연계)",
  pce: "인사관리 연계",
  pub: "확인 중",
  diff: "급여 계산 결과를 FI 전표와 CO 코스트센터로 전기하는 타모듈 연계. FI 컨설턴트가 실무에서 맞닥뜨리는 대표 HR 연결 포인트.",
  help: [],
  tags: ["CO", "전표"], related: ["co-ccenter", "co-celem", "org-company-code"],
  eccSame: true
},
{
  id: "co-auc-settle", area: "CO", item: "AuC 정산 (건설가계정 → 자산)",
  ecc: "자산회계 > 기말결산 > 건설가계정(AuC) 정산",
  pce: "자산회계 > 기말결산",
  pub: "IMG 표시 > 회계 > 자본 비용 관리 > 자본 비용 정산",
  diff: "건설 중인 자산(AuC)에 모인 원가를 본자산으로 정산하는 AA-CO 연계의 대표 케이스. 자산 정산프로파일(aa-settlement)과 함께 본다.",
  help: [],
  tags: ["CO"], related: ["aa-settlement", "co-settle", "co-order", "aa-acctdet"],
  eccSame: true
},
  {
    "id": "grc-ara",
    "area": "내부통제",
    "item": "SoD 위험 분석(ARA)",
    "ecc": "GRC Access Control 애드온 (ARA)",
    "pce": "GRC Access Control 애드온 (ARA)",
    "pub": "확인 중",
    "diff": "사용자·역할·프로필·HR 개체를 교차 시스템으로 분석해 SoD 충돌을 찾는다. ECC·PCE는 GRC Access Control 애드온에서 동작하며, 변경 시뮬레이션으로 신규 위험 도입을 사전에 막을 수 있다.",
    "help": [],
    "tags": ["SoD", "권한", "리스크"],
    "related": []
  },
  {
    "id": "grc-mitigating",
    "area": "내부통제",
    "item": "완화통제 등록",
    "ecc": "GRC Access Control 애드온",
    "pce": "GRC Access Control 애드온",
    "pub": "확인 중",
    "diff": "위험에 완화통제를 연결하고 유효기간·승인자·모니터를 지정한다. 충돌·위험 행위가 발생하면 담당자에게 에스컬레이션 알림이 간다.",
    "help": [],
    "tags": ["완화통제", "SoD"],
    "related": []
  },
  {
    "id": "grc-arm",
    "area": "내부통제",
    "item": "접근 요청 관리(ARM)",
    "ecc": "GRC Access Control 애드온 (ARM)",
    "pce": "GRC Access Control 애드온 (ARM)",
    "pub": "확인 중",
    "diff": "권한 요청·승인을 티켓 기반 워크플로로 관리한다. 요청 제출·승인 단계에서 ARA를 함께 돌릴 수 있고, 부재 시 대리인 승인도 지원한다.",
    "help": [],
    "tags": ["워크플로", "권한요청"],
    "related": []
  },
  {
    "id": "grc-firefighter",
    "area": "내부통제",
    "item": "파이어파이터(긴급 접근)",
    "ecc": "",
    "pce": "",
    "pub": "확인 중",
    "diff": "평상시엔 없는 긴급 권한을 일정 기간 부여하고 사용 내역을 남기는 방식이다. 원문에는 절차 제목만 있어 세부 단계는 별도 확인이 필요하다.",
    "help": [],
    "tags": ["긴급권한", "감사"],
    "related": []
  },
  {
    "id": "grc-role-derivation",
    "area": "내부통제",
    "item": "마스터→파생 역할 전파",
    "ecc": "PFCG (프로파일 생성기)",
    "pce": "PFCG (프로파일 생성기)",
    "pub": "확인 중",
    "diff": "마스터 역할을 템플릿으로 삼아 회사코드별 파생 역할을 만든다. 마스터의 권한을 파생 역할로 전파한 뒤 조직값을 유지하는 구조로, PFCG에서 직접 유지한다.",
    "help": [],
    "tags": ["역할", "PFCG", "조직값"],
    "related": []
  },
  {
    "id": "ml-ckmlcp-steps",
    "area": "CO",
    "item": "실제원가계산 실행(CKMLCP) 8단계",
    "ecc": "관리회계 > 제품원가통제 > 실제원가계산/자재원장 > 실제원가계산 (CKMLCP)",
    "pce": "관리회계 > 제품원가통제 > 실제원가계산/자재원장 > 실제원가계산 (CKMLCP)",
    "pub": "확인 중",
    "diff": "ECC에서는 ML 없이 표준원가·이동평균으로 마감했지만, S/4에서는 CKMLCP 8단계 런이 실제원가 확정의 표준 절차다. 순서 결정→단일·다수준 가격결정→소비·WIP 재평가→사후마감→가격 표시 순서로 돌린다.",
    "help": [],
    "tags": ["자재원장", "실제원가계산", "CKMLCP"],
    "related": []
  },
  {
    "id": "ml-parallel-valuation",
    "area": "CO",
    "item": "병렬 통화/평가·이전가격",
    "ecc": "관리회계 > 일반통제 > 다중평가접근/이전가격 (SPRO)",
    "pce": "관리회계 > 일반통제 > 다중평가접근/이전가격 (SPRO)",
    "pub": "확인 중",
    "diff": "여러 통화·평가(법적/그룹)로 재고를 병행 평가하려면 ML이 필수다. ECC에서는 선택 사항이었으나 S/4에서는 ML이 강제라 병렬 평가가 기본 전제가 된다.",
    "help": [],
    "tags": ["자재원장", "이전가격", "병렬평가"],
    "related": []
  },
  {
    "id": "ml-inventory-revaluation",
    "area": "결산",
    "item": "재고 재평가 여부(BSX/LKW)",
    "ecc": "CKMLCP 사후마감 단계의 '재고 재평가' 체크박스",
    "pce": "CKMLCP 사후마감 단계의 '재고 재평가' 체크박스",
    "pub": "확인 중",
    "diff": "재평가를 선택하면 마감 기간 가격통제가 S에서 V로 바뀌고 차이가 재고계정(BSX)으로 롤링된다. 선택하지 않으면 가격통제는 S로 남고 차이가 발생계정(LKW)으로 간다. 둘 다 마감 취소는 가능하다.",
    "help": [],
    "tags": ["자재원장", "결산", "BSX"],
    "related": []
  },
  {
    "id": "ml-consumption-cc-cf",
    "area": "CO",
    "item": "소비재평가 CC/CF·이동유형그룹",
    "ecc": "관리회계 > 제품원가통제 > 실제원가계산/자재원장 > 자재갱신 > 자재원장의 이동유형그룹 지정",
    "pce": "관리회계 > 제품원가통제 > 실제원가계산/자재원장 > 자재갱신 > 자재원장의 이동유형그룹 지정",
    "pub": "확인 중",
    "diff": "소비재평가를 켜면 비자재 입고처(코스트센터·WBS·매출원가 등)로 간 차이가 FI 계정에 다시 반영된다. 이동유형별로 계정만(CC) 볼지, 계정+원가대상(CF)까지 볼지를 이동유형그룹에서 정한다.",
    "help": [],
    "tags": ["자재원장", "소비재평가", "이동유형그룹"],
    "related": []
  },
  {
    "id": "ml-cogs-split",
    "area": "CO",
    "item": "COGS 원가요소별 계정 분할",
    "ecc": "(지원 안 됨 — 단일 COGS 계정)",
    "pce": "사용자정의에서 계정별 원가요소 분할 설정",
    "pub": "확인 중",
    "diff": "ECC에서는 COGS가 단일 계정이었지만, S/4에서는 원가요소 분할을 따라 직접재료·노무·기계비 등 여러 계정으로 나눠 전기할 수 있다. 계정 기반 CO-PA가 ACDOCA를 함께 쓰는 전제가 된다.",
    "help": [],
    "tags": ["자재원장", "매출원가", "CO-PA"],
    "related": []
  },
  {
    "id": "ml-wip-revaluation",
    "area": "CO",
    "item": "WIP 재평가",
    "ecc": "CKMLCP 6단계 WIP 재평가",
    "pce": "CKMLCP 6단계 WIP 재평가",
    "pub": "확인 중",
    "diff": "아직 진행 중인 생산오더(DLV·TECO 아님)에서 소비된 자재의 차이는 WIP 계정으로 비례 배분된다. 마감 런의 한 단계로 자동 처리된다.",
    "help": [],
    "tags": ["자재원장", "WIP", "결산"],
    "related": []
  },
  {
    "id": "ml-price-marking",
    "area": "CO",
    "item": "실제원가의 표준원가 표시",
    "ecc": "CKMLCP 8단계 자재가격 표시",
    "pce": "CKMLCP 8단계 자재가격 표시",
    "pub": "확인 중",
    "diff": "ML에서 계산된 실제원가를 다음 달 이후의 표준원가로 표시해 둘 수 있다. 다만 마감한 달의 바로 다음 달은 상품 이동이 이미 발생했을 수 있어, 빠르면 마감 2개월 뒤 기간부터 표시 가능하다.",
    "help": [],
    "tags": ["자재원장", "표준원가"],
    "related": []
  },
  {
    "id": "ml-migration-m10-m11",
    "area": "결산",
    "item": "ML 마이그레이션 M10/M11",
    "ecc": "(해당 없음 — 전환 활동)",
    "pce": "S/4HANA Finance 전환 > 데이터 마이그레이션 시작·모니터링 (SPRO)",
    "pub": "확인 중",
    "diff": "ECC→S/4 전환 시 ML 데이터 마이그레이션은 필수 단계다. M10에서 마스터 데이터를 ML 통화로 채우고 ACDOCA로 이관하고, M11에서 구매·생산오더 히스토리를 ML 통화로 변환한다.",
    "help": [],
    "tags": ["자재원장", "마이그레이션"],
    "related": []
  },
  {
    "id": "ml-migration-m20-m21",
    "area": "결산",
    "item": "ML 마이그레이션 검증 M20/M21",
    "ecc": "(해당 없음 — 전환 활동)",
    "pce": "FINS_MIG_STATUS 모니터링",
    "pub": "확인 중",
    "diff": "M10/M11 실행 뒤에는 M20/M21로 ACDOCA와 비교 검증한다. 진행 상황은 FINS_MIG_STATUS에서 모니터링하고, 전부 끝나면 '마이그레이션 완료'로 확정해야 상품 이동이 허용된다. 실제원가를 쓰던 곳은 마이그레이션 전에 CKMLCP 사후마감을 끝내야 한다.",
    "help": [],
    "tags": ["자재원장", "마이그레이션", "FINS_MIG_STATUS"],
    "related": []
  },
  {
    "id": "ml-fx-exclusion",
    "area": "CO",
    "item": "가격결정 시 환율차이 제외",
    "ecc": "CKMLCP 사용자정의 옵션",
    "pce": "CKMLCP 사용자정의 옵션",
    "pub": "확인 중",
    "diff": "환율 영향을 받는 회사는 단일·다수준 가격결정에서 환율차이를 제외하는 옵션을 쓸 수 있다. 켜면 환율차이는 손익에 남고 대차대조표 재고 평가에는 반영되지 않아, 컨트롤러가 환율 제외 재고 변동을 따로 추적할 수 있다.",
    "help": [],
    "tags": ["자재원장", "환율차이"],
    "related": []
  },
  {
    "id": "lease-recognition",
    "area": "자산회계",
    "item": "리스회계 인식 방식 (IFRS16)",
    "ecc": "",
    "pce": "",
    "pub": "확인 중",
    "diff": "IFRS16에 따라 리스 계약의 사용권자산과 리스부채를 재무상태표에 계상한다. ECC에는 내장 리스회계 기능이 없어 별도 애드온이나 수기 처리로 대응하고, S/4HANA부터 RE-FX 기반 리스회계가 내장됐다. Public의 지원 범위는 별도 확인이 필요하다.",
    "help": [],
    "tags": ["리스", "IFRS16", "사용권자산"],
    "related": []
  },
  {
    "id": "lease-prepaid-process",
    "area": "자산회계",
    "item": "선급비용→리스 전환 프로세스",
    "ecc": "",
    "pce": "",
    "pub": "확인 중",
    "diff": "선급비용 계정그룹으로 전표가 생성되면 선급비용 마스터가 만들어지고, 회계팀이 리스 대상 여부를 건건이 확인해 마스터 상태를 변경하는 현장 프로세스다. 리스 대상이면 선급비용 대체 후 임차료 부분을 반대분개로 되돌려 사용권자산으로 합산한다. 온라인몰처럼 엑셀로 관리하는 곳은 마이그레이션 시 마스터·대체전표 내역을 데이터로 생성하는 방식도 쓴다.",
    "help": [],
    "tags": ["리스", "선급비용", "사용권자산"],
    "related": []
  },
  {
    "id": "tmp-bp-relcat",
    "area": "조직구조",
    "item": "BP 관계 카테고리 커스텀과 KNVK 동기화",
    "ecc": "CVI 설정 > BP 관계 카테고리 정의 (확인 중)",
    "pce": "S/4HANA CVI 설정 (확인 중)",
    "pub": "확인 중",
    "diff": "BP 관계 카테고리를 커스텀으로 추가하면 CVI 동기화를 통해 고객·공급처처 마스터의 연락처 정보(KNVK)에 반영되는 지점이 생긴다. 관계 유형 설계가 마스터 동기화에 직접 영향을 준다.",
    "help": [],
    "tags": ["BP", "CVI", "KNVK", "마스터"],
    "related": []
  },
  {
    "id": "tmp-cvi-sync",
    "area": "조직구조",
    "item": "CVI 고객·공급처처 동기화",
    "ecc": "CVI 선택 적용 (확인 중)",
    "pce": "S/4HANA 내장 CVI (확인 중)",
    "pub": "확인 중",
    "diff": "ECC에서는 CVI가 선택 적용이었지만 S/4HANA에서는 BP 기반이 표준이라 동기화가 내장된다. 동기화 메서드(MAP_BPS_TO_CUSTOMERS)와 관계 유형 상수(rel_type_contact)가 매핑의 핵심 지점이다.",
    "help": [],
    "tags": ["BP", "CVI", "동기화"],
    "related": []
  },
  {
    "id": "etc-mat-master",
    "area": "타모듈 연결",
    "item": "온라인몰 상품등록 → SAP 자재마스터 연계",
    "ecc": "MM01 자재마스터 등록 (확인 중)",
    "pce": "Fiori 자재마스터 앱 (확인 중)",
    "pub": "확인 중",
    "diff": "온라인몰에서 신규 상품을 등록하면 SAP 자재마스터 등록 단계가 별도로 있다. 상품정보(백오피스)와 SAP 자재마스터가 따로 놀지 않도록 등록 시점을 맞추는 것이 현장의 포인트다.",
    "help": [],
    "tags": ["자재마스터", "온라인몰", "인터페이스"],
    "related": []
  },
  {
    "id": "etc-mass-clearing",
    "area": "AR",
    "item": "일일 정산 → 대량전표 → 미수금 반제",
    "ecc": "대량전표 파일 업로드·배치 전기 (확인 중)",
    "pce": "Fiori 자동반제 (확인 중)",
    "pub": "확인 중",
    "diff": "일일 정산 내역을 대량전표 파일로 만들어 올리고, 오류를 검토·수정한 뒤 SAP에서 미수금을 반제한다. 파일 기반 일괄 처리라 오류내역 확인 단계가 마감의 병목이 되기 쉽다.",
    "help": [],
    "tags": ["대량전표", "미수금", "반제", "정산"],
    "related": []
  },
  {
    "id": "etc-return-cycle",
    "area": "타모듈 연결",
    "item": "반품 풀사이클 (요청→회수→귀책판정→환불)",
    "ecc": "SD 반품오더 + MM 반품 입고 + FI 환불 전표 (확인 중)",
    "pce": "Fiori 반품 프로세스 (확인 중)",
    "pub": "확인 중",
    "diff": "SD의 반품 요청·접수에서 시작해 MM의 반품 입고·검수, 귀책판정을 거쳐 FI의 환불 전표까지 이어진다. 모듈을 넘나드는 풀사이클이라 귀책판정이 끊기는 지점이 되기 쉽다.",
    "help": [],
    "tags": ["반품", "SD", "MM", "환불"],
    "related": []
  },
  {
    "id": "im-auc-settle",
    "area": "자산회계",
    "item": "AUC 정산 (건설중인자산)",
    "ecc": "",
    "pce": "",
    "pub": "확인 중",
    "diff": "내부오더·WBS에 모인 비용 중 자본화 대상은 건설중인자산(AUC)으로 정산하고, 준공 시 본자산으로 대체한다. ECC·PCE·Public 모두 개념은 동일하며, 정산 트랜잭션의 버전별 차이는 별도 검증이 필요하다.",
    "help": [],
    "tags": ["자산", "정산", "AUC"],
    "related": []
  },
  {
    "id": "im-invest-program",
    "area": "자산회계",
    "item": "투자 프로그램 정의",
    "ecc": "",
    "pce": "",
    "pub": "확인 중",
    "diff": "연간 투자 계획을 계층 구조(최대 99레벨)로 관리하는 최상위 마스터. 프로그램 정의·구조·위치로 구성되며 지출요청과 조치를 묶는다. 투자관리(IM) 모듈의 출발점이다.",
    "help": [],
    "tags": ["자산", "투자관리", "마스터"],
    "related": []
  },
  {
    "id": "conv-readiness",
    "area": "타모듈 연결",
    "item": "전환 준비 상태 확인",
    "ecc": "SE38 > /SDF/RC_START_CHECK",
    "pce": "",
    "pub": "확인 중",
    "diff": "ECC→S/4HANA 전환 전 단순화 항목을 점검하는 보고서(SE38에서 /SDF/RC_START_CHECK 실행). PCE 브라운필드 전환의 출발점이며, Public은 그린필드라 해당 절차가 없다.",
    "help": [],
    "tags": ["전환", "S/4HANA"],
    "related": []
  },
  {
    "id": "conv-sum",
    "area": "타모듈 연결",
    "item": "SUM을 이용한 업그레이드",
    "ecc": "Software Update Manager",
    "pce": "",
    "pub": "확인 중",
    "diff": "단순화 항목 해소 후 릴리스 업그레이드·지원패키지 적용에 쓰는 도구. Public은 그린필드 전환만 지원하므로 SUM 절차가 없다.",
    "help": [],
    "tags": ["전환", "업그레이드"],
    "related": []
  },
  {
    "id": "conv-cutover",
    "area": "타모듈 연결",
    "item": "컷오버 계획",
    "ecc": "",
    "pce": "",
    "pub": "확인 중",
    "diff": "SIT·UAT 승인 후 본전환 일정을 계획하는 단계. 테스트에서 수행할 작업과 프로덕션 전환 일정을 사업부 담당자와 함께 잡는다. Public은 Migrate Your Data 앱으로 이행한다.",
    "help": [],
    "tags": ["전환", "컷오버"],
    "related": []
  },
  {
    "id": "act-methodology",
    "area": "타모듈 연결",
    "item": "구현 방법론",
    "ecc": "ASAP 방법론",
    "pce": "SAP Activate",
    "pub": "SAP Activate (Fit-to-Standard 필수)",
    "diff": "ECC는 ASAP, S/4HANA는 Activate 6단계(Discover→Prepare→Explore→Realize→Deploy and Run)를 쓴다. Public은 Fit-to-Standard가 필수이며 표준 프로세스에서 벗어나는 확장이 제한된다.",
    "help": [],
    "tags": ["방법론", "구축"],
    "related": []
  },
];

// 지식그래프용 노드/엣지 (entries에서 자동 생성 + 개념 노드 추가)
const GRAPH_CONCEPTS = [
  {id: "c-acdoca", label: "ACDOCA", type: "table"},
  {id: "c-bp", label: "Business Partner", type: "master"},
  {id: "c-cvi", label: "CVI", type: "concept"},
  {id: "c-fiori", label: "Fiori", type: "app"},
  {id: "c-newaa", label: "New AA", type: "concept"},
  {id: "c-ml", label: "Material Ledger", type: "concept"},
  {id: "c-fcc", label: "결산 콕핏", type: "app"}
];
const GRAPH_LINKS = [
  {from: "c-acdoca", to: "c-bp", label: "연관"},
  {from: "c-bp", to: "c-cvi", label: "동기화"},
  {from: "c-acdoca", to: "c-newaa", label: "연계"},
  {from: "c-acdoca", to: "c-ml", label: "통합"},
  {from: "c-fiori", to: "c-bp", label: "앱 제공"},
  {from: "c-fiori", to: "c-fcc", label: "통합"},
  {from: "c-newaa", to: "c-fcc", label: "이월 통합"}
];