// 현장 스케치 데이터 — 계속 추가하면서 고도화
// category: 결산·마감 / 전표·전기 / 원가·자재 / 마스터·조직 / MM·SD 연계 / 회계 일반
// date: 20X6.10 형태 (연도 마스킹)
const SKETCHES = [
  {
    id: "sk-wip-mig",
    category: "원가·자재",
    date: "20X4.12",
    title: "시스템 신규 오픈 시 재공품 잔액 Mig 방법",
    source: "blog",
    url: "https://hksap.tistory.com/849",
    comment: "새 시스템 오픈 때 재공품 잔액을 어떻게 옮기느냐는 제조업 FI/CO의 단골 난제다. 방법론이 정해져 있지 않으면 오픈 직전까지도 논쟁이 이어지는 주제라, 미리 정리해 둔 글이 현장에서 바로 써먹힌다.",
    configs: ["co-ml"],
    terms: ["actual-costing", "material-ledger", "wip-accounting"],
  },
  {
    id: "sk-wip-provision",
    category: "원가·자재",
    date: "20X4.09",
    title: "재공품 미실현원가 충당금 관련",
    source: "blog",
    url: "https://hksap.tistory.com/847",
    comment: "재공품에 대한 미실현원가 충당금을 잡아야 하는지, 잡는다면 어느 시점에 잡는지 — 결산 때마다 회계팀과 실랑이하는 주제다. 기준을 정리해 둔 글이 실무 판단에 도움이 된다.",
    configs: ["co-ml"],
    terms: ["actual-costing", "wip-accounting"],
  },
  {
    id: "sk-ml-closing-alloc",
    category: "결산·마감",
    date: "20X4.09",
    title: "자재원장 결산 후 배부하지 않음과 배부되지 않음 관련",
    source: "blog",
    url: "https://hksap.tistory.com/845",
    comment: "자재원장 결산에서 '배부하지 않음'과 '배부되지 않음'은 비슷해 보이지만 원인과 대응이 완전히 다르다. 마감 날 밤에 마주치면 당황하기 쉬운 메시지라 정리 가치가 크다.",
    configs: ["co-alloc", "co-ml"],
    terms: ["actual-costing", "material-ledger-closing"],
  },
  {
    id: "sk-profit-center-segment",
    category: "마스터·조직",
    date: "20X4.09",
    title: "손익센터와 세그먼트 부분",
    source: "blog",
    url: "https://hksap.tistory.com/844",
    comment: "손익센터와 세그먼트는 비슷해 보이지만 용도가 다르다. 전표분할과 함께 이해해야 하는 개념이라 FI 결산 담당자라면 한 번쯤 정리하고 넘어갈 주제다.",
    configs: ["co-prctr", "gl-docsplit"],
    terms: ["document-splitting", "profit-center"],
  },
  {
    id: "sk-real-cost-object",
    category: "원가·자재",
    date: "20X4.07",
    title: "Real Cost Object 관련",
    source: "blog",
    url: "https://hksap.tistory.com/839",
    comment: "실제원가를 계산할 때 기준이 되는 '실원가 대상' 개념. 말은 쉬운데 막상 시스템에서 어디에 매핑되는지 헷갈리는 경우가 많아 정리해 둘 만하다.",
    configs: ["co-ml"],
    terms: ["actual-costing"],
  },
  {
    id: "sk-cost-component",
    category: "원가·자재",
    date: "20X4.06",
    title: "원가구성요소 관련",
    source: "blog",
    url: "https://hksap.tistory.com/832",
    comment: "제품원가를 재료비·노무비·경비로 나누는 원가구성요소. 원가 담당자와 대화할 때 기본이 되는 개념이라 FI 쪽에서도 알아 두면 좋다.",
    configs: ["co-costvar"],
    terms: ["multilevel-costing", "production-costing"],
  },
  {
    id: "sk-copa-topdown",
    category: "결산·마감",
    date: "20X4.06",
    title: "CO-PA 탑다운 배부 관련 자료",
    source: "blog",
    url: "https://hksap.tistory.com/825",
    comment: "CO-PA에서 위에서 아래로 배부하는 탑다운 배부. 수익성분석을 쓰는 현장에서 결산 때마다 돌리는 로직이라 흐름을 알아 두면 좋다.",
    configs: ["co-alloc", "co-margin"],
    terms: ["allocation", "profitability-analysis"],
  },
  {
    id: "sk-internal-order-public",
    category: "마스터·조직",
    date: "20X3.11",
    title: "S/4HANA Cloud Public edition Internal Order관련",
    source: "blog",
    url: "https://hksap.tistory.com/814",
    comment: "Public Edition에서 내부오더가 어떻게 동작하는지 정리한 글. Public은 CO 설정이 제한적이라 되는 것과 안 되는 것을 구분해 두는 게 중요하다.",
    configs: ["co-order"],
    terms: ["internal-order"],
  },
  {
    id: "sk-material-ledger-actual",
    category: "원가·자재",
    date: "20X3.11",
    title: "Material Ledgers/ Actual Costing 관련",
    source: "blog",
    url: "https://hksap.tistory.com/812",
    comment: "자재원장과 실제원가계산의 관계를 정리한 글. 표준원가와 실제원가의 차이가 어디서 발생하는지 이해하는 출발점이다.",
    configs: ["co-ml", "xmod-ml"],
    terms: ["actual-costing", "material-ledger"],
  },
  {
    id: "sk-ml-table",
    category: "원가·자재",
    date: "20X3.07",
    title: "ML Table 관련",
    source: "blog",
    url: "https://hksap.tistory.com/773",
    comment: "자재원장 뒤에 있는 테이블들 정리. 장애나 마감 이슈 때 테이블을 직접 뒤져야 하는 순간이 오는데, 그때 어디를 봐야 하는지 아는 것과 모르는 것의 차이가 크다.",
    configs: ["xmod-ml"],
    terms: ["material-ledger"],
  },
  {
    id: "sk-miro-split",
    category: "MM·SD 연계",
    date: "20X3.02",
    title: "MIRO 송장처리 시 FI전표 분할 관련",
    source: "blog",
    url: "https://hksap.tistory.com/727",
    comment: "MIRO로 송장을 처리할 때 FI 전표가 분할되는 케이스. MM과 FI 경계에서 생기는 이슈라 양쪽 지식이 함께 필요하다.",
    configs: ["close-grir", "gl-docsplit"],
    terms: ["document-splitting", "invoice-verification"],
  },
  {
    id: "sk-reversal-test",
    category: "전표·전기",
    date: "20X3.09",
    title: "역분개전표 역분개 테스트관련",
    source: "blog",
    url: "https://hksap.tistory.com/784",
    comment: "역분개한 전표를 다시 역분개하는 테스트. 말장난 같지만 결산 조정에서 실제로 마주치는 상황이라, 동작 방식을 미리 확인해 두면 실수를 줄일 수 있다.",
    configs: ["gl-reversal-reason"],
    terms: ["reversal"],
  },
  {
    id: "sk-offbook-assets",
    category: "회계 일반",
    date: "",
    title: "장부외자산 1천여 건 생성 및 역분개 처리",
    source: "facebook",
    url: "",
    comment: "장부에 없던 자산 1천여 건을 한 번에 생성하고 역분개까지 처리한 현장 기록. 대량 데이터 처리에서 번호·일자·역분개 사유를 어떻게 통제하는지 보여주는 사례다.",
    configs: ["aa-class", "gl-reversal-reason"],
    terms: ["reversal"],
  },
  {
    id: "sk-card-dup",
    category: "전표·전기",
    date: "",
    title: "법인카드 경비 전표 중복 생성 — 락 오브젝트 통과 사례",
    source: "facebook",
    url: "",
    comment: "법인카드 경비 전표를 두 번 눌러 중복 생성된 사건. 락 오브젝트를 통과해 들어온 케이스로, 인터페이스 전표에서 중복 방지가 왜 중요한지 보여준다.",
    configs: ["gl-doc-type"],
    terms: ["document"],
  },
  {
    id: "sk-wip-actual-public",
    category: "회계 일반",
    date: "",
    title: "WIP at Actual — Public에서 전표 나온 날",
    source: "facebook",
    url: "",
    comment: "Public Edition에서 WIP at Actual로 전표가 처음 나온 날의 기록. Public에서 CO가 돌아간다는 것 자체가 관심사라 현장감이 있다.",
    configs: ["co-ml"],
    terms: ["actual-costing", "wip-accounting"],
  },
  {
    id: "sk-co-settle-mismatch",
    category: "회계 일반",
    date: "",
    title: "CO 결산 검증 — 타계정이 원계정 안 따라감",
    source: "facebook",
    url: "",
    comment: "CO 결산 검증 중 타계정이 원계정을 따라가지 않은 이슈. 배부·분배 로직에서 계정 매핑이 어긋나면 생기는 전형적인 결산 트러블이다.",
    configs: ["co-alloc", "co-close"],
    terms: ["allocation"],
  },
  {
    id: "sk-first-close",
    category: "결산·마감",
    date: "",
    title: "오픈 후 첫 결산 드디어 끝",
    source: "facebook",
    url: "",
    comment: "시스템 오픈 후 첫 결산을 마친 날의 기록. 오픈 첫 달 결산이 왜 힘든지 겪어본 사람만 아는 감정이 담겨 있다.",
    configs: ["close-cockpit"],
    terms: ["closing-cockpit"],
  },
  {
    id: "sk-gl-ml-mismatch",
    category: "회계 일반",
    date: "",
    title: "FI G/L 잔액 vs CO-ML 금액 불일치 — OSS 재등록",
    source: "evernote",
    url: "",
    comment: "운영 시스템에서 FI G/L 잔액과 CO 자재원장 금액이 맞지 않아 OSS에 재등록 요청한 사례. FI와 CO가 어긋나는 순간이 왜 생기는지 보여주는 트러블슈팅 기록이다.",
    configs: ["co-ml", "xmod-ml"],
    terms: ["actual-costing", "material-ledger"],
  },
  {
    id: "sk-overseas-go-live-close",
    category: "회계 일반",
    date: "",
    title: "해외법인 오픈 후 첫 월결산 — FI/CO 일치로 마감",
    source: "evernote",
    url: "",
    comment: "해외법인 오픈 후 8월 결산을 물류 D+2, 재무/원가 D+6에 FI/CO 일치로 마친 기록. 결산 스케줄이 현장에서 어떻게 돌아가는지 보여주는 사례다.",
    configs: ["close-cockpit"],
    terms: ["closing-cockpit"],
  },
  {
    id: "sk-lines-999",
    category: "전표·전기",
    date: "",
    title: "999라인 넘는 전표",
    source: "keep",
    url: "",
    comment: "한 전표에 999라인이 넘는 경우에 대한 메모. 대량 라인 전표는 성능·번호·출력에서 별도 고려가 필요해 현장에서 자주 화젯거리가 된다. S/4 자산취득·매각은 거래전표와 평가전표가 고정자산기술적임시계정으로 분리돼 2차전표가 생기는데, 자산 1건당 2라인이 생겨 거래전표 499라인까지만 가능하고 500라인부터는 999라인을 초과해 에러가 난다.",
    links: [
      { type: "blog", title: "[AA] 자산취득 및 매각 2차전표 관련", url: "https://hksap.tistory.com/786" }
    ],
    configs: ["gl-doc-type", "aa-acctdet"],
    terms: ["document", "line-item"],
  },
  {
    id: "sk-blog-01",
    category: "전표·전기",
    date: "20X5.05",
    title: "전표입력 Fiori 앱에서 그룹통화 변경",
    source: "blog",
    url: "https://hksap.tistory.com/861",
    comment: "Fiori 전표 입력에서 그룹통화 금액을 바꾸는 방법을 정리한 글이다. GUI와 Fiori 앱의 동작이 달라 현장에서 헷갈리기 쉬운 지점이다.",
    configs: [],
    terms: [],
  },
  {
    id: "sk-blog-02",
    category: "전표·전기",
    date: "20X5.05",
    title: "SPGL 관련",
    source: "blog",
    url: "https://hksap.tistory.com/860",
    comment: "특별 G/L(SPGL)이 무엇인지, 왜 쓰는지를 정리한 참고자료다. 선수금·어음 같은 보조부 관리 대상을 이해하는 데 도움이 된다.",
    configs: [],
    terms: [],
  },
  {
    id: "sk-blog-03",
    category: "전표·전기",
    date: "",
    title: "전기일 <> 반제일 Case",
    source: "blog",
    url: "https://hksap.tistory.com/848",
    comment: "반제일은 전기일보다 먼저일 수 없다는 SAP 기본 규칙을 다룬 글. 반제 전표 처리 시 날짜 오류가 나면 가장 먼저 의심해볼 포인트다.",
    configs: [],
    terms: [],
  },
  {
    id: "sk-blog-04",
    category: "전표·전기",
    date: "20X4.07",
    title: "F110 자동지급 처리 시 지급전표 필드 대체룰 처리 관련",
    source: "blog",
    url: "https://hksap.tistory.com/841",
    comment: "F110 지급전표의 참조 필드를 대체룰로 채우는 고객 요건을 정리한 글. ECC와 S/4HANA의 차이, 디버깅 참고자료를 함께 모았다.",
    configs: [],
    terms: [],
  },
  {
    id: "sk-blog-05",
    category: "결산·마감",
    date: "20X4.07",
    title: "F.19 GR/IR 미착대체 관련",
    source: "blog",
    url: "https://hksap.tistory.com/834",
    comment: "결산 때마다 나오는 GR/IR 미착·미지급비용 대체를 F.19로 처리하는 방법 정리. T-Code를 잊기 쉬워 메모해 둔 실무 치트시트다.",
    configs: [],
    terms: [],
  },
  {
    id: "sk-blog-06",
    category: "전표·전기",
    date: "20X4.06",
    title: "F5080 Consolidated companies XXXX and ' ' are different",
    source: "blog",
    url: "https://hksap.tistory.com/831",
    comment: "관계사 BP와 일반 거래처가 한 전표에 섞이면 나는 F5080 에러와, 전표유형의 회사간거래 체크로 해결한 기록.",
    configs: [],
    terms: [],
  },
  {
    id: "sk-blog-07",
    category: "전표·전기",
    date: "20X4.04",
    title: "AR & AP 일괄 F110 처리 관련",
    source: "blog",
    url: "https://hksap.tistory.com/821",
    comment: "F110으로 AR 입금·AP 지급·상계까지 한 번에 처리한 테스트 기록. 마스터의 반제 허용 체크가 핵심 포인트다.",
    configs: [],
    terms: [],
  },
  {
    id: "sk-blog-08",
    category: "마스터·조직",
    date: "20X4.02",
    title: "건설중인자산 mig시 전기일 관련",
    source: "blog",
    url: "https://hksap.tistory.com/820",
    comment: "건설중인자산 이관 시 거래유형 100은 이관일, 900은 1월 1일로 들어가는 SAP 표준 규칙 정리. 현업 클레임 대응용 근거 메모다.",
    configs: [],
    terms: [],
  },
  {
    id: "sk-blog-09",
    category: "원가·자재",
    date: "20X5.01",
    title: "표준원가 추정시 외자 적용 환율 관련",
    source: "blog",
    url: "https://hksap.tistory.com/857",
    comment: "표준원가 추정 때 외자에 P타입 환율만 넣으면 에러가 나고 M타입까지 넣어야 통과됐던 사례다. 추정 직전 체크리스트로 쓸 만하다.",
    configs: [],
    terms: [],
  },
  {
    id: "sk-blog-10",
    category: "MM·SD 연계",
    date: "20X5.01",
    title: "MM 입고시 회계전표 안나오게 설정",
    source: "blog",
    url: "https://hksap.tistory.com/856",
    comment: "MM 입고 시점에 회계전표가 안 나오게 하고 송장 시점에 처리하는 설정 방법을 정리했다. GR/IR 없이 가는 요건에서 쓴다.",
    configs: [],
    terms: [],
  },
  {
    id: "sk-blog-11",
    category: "MM·SD 연계",
    date: "20X5.01",
    title: "OBYC GBB-VAX GBB-VAY 관련",
    source: "blog",
    url: "https://hksap.tistory.com/855",
    comment: "OBYC의 GBB-VAX/VAY가 언제 어느 계정으로 빠지는지 정리한 글이다. 매출원가 계정 결정의 기본기라 MM-FI 연계의 출발점이다.",
    configs: [],
    terms: [],
  },
  {
    id: "sk-blog-12",
    category: "원가·자재",
    date: "20X4.12",
    title: "외주생산시 제품 입고시점 제조간접부서의 경비 처리 관련",
    source: "blog",
    url: "https://hksap.tistory.com/854",
    comment: "외주생산으로 제품이 입고될 때 제조간접부서의 재료비·노무비·경비를 어떻게 처리할지 정리한 글이다. 자체 생산라인이 없는 구조에서 꼭 마주치는 주제다.",
    configs: [],
    terms: [],
  },
  {
    id: "sk-blog-13",
    category: "원가·자재",
    date: "20X4.12",
    title: "부산물의 실제원가 관련",
    source: "blog",
    url: "https://hksap.tistory.com/853",
    comment: "부산물의 실제원가를 어떻게 구하는지 정리한 글이다. BOM에 마이너스로 달고 순실현가치로 추정하는 실무 팁이 담겼다.",
    configs: [],
    terms: [],
  },
  {
    id: "sk-blog-14",
    category: "원가·자재",
    date: "20X4.12",
    title: "수입자재 표준원가 추정 관련",
    source: "blog",
    url: "https://hksap.tistory.com/852",
    comment: "수입자재 표준원가에 부대비까지 반영해 추정하는 방법을 정리했다. 코스트시트를 쓰는 실무 접근이 담겼다.",
    configs: [],
    terms: [],
  },
  {
    id: "sk-blog-15",
    category: "원가·자재",
    date: "20X4.12",
    title: "반제품을 구매시 처리방법 관련",
    source: "blog",
    url: "https://hksap.tistory.com/851",
    comment: "구매와 생산이 섞인 반제품을 RoH/HALB 중 어떻게 분류할지, 평가유형 분리의 실무 논쟁을 정리한 글.",
    configs: [],
    terms: [],
  },
  {
    id: "sk-blog-16",
    category: "원가·자재",
    date: "20X4.12",
    title: "공정중 불량 처리방법 관련",
    source: "blog",
    url: "https://hksap.tistory.com/850",
    comment: "공정 중 불량은 재료비 투입을 취소하고 가공비만 남겨 TECO·정산하는 가이드. CO/PP 현장의 단골 질문이다.",
    configs: [],
    terms: [],
  },
  {
    id: "sk-blog-17",
    category: "회계 일반",
    date: "",
    title: "연결회계 관련 참고자료",
    source: "blog",
    url: "https://hksap.tistory.com/826",
    comment: "지분법과 연결회계가 본질적으로 같다는 외부 칼럼 소개. 그룹리포팅 프로젝트 준비용 스터디 메모다.",
    configs: [],
    terms: [],
  },
  {
    id: "sk-blog-18",
    category: "회계 일반",
    date: "20X3.03",
    title: "리스채권과 투자부동산관련",
    source: "blog",
    url: "https://hksap.tistory.com/741",
    comment: "IFRS 16 리스채권과 IAS 40 투자부동산의 구분을 정리한 글. SAP 표준 리스 회계 적용 방안을 논의한 메모다.",
    configs: [],
    terms: [],
  },
  {
    id: "sk-blog-19",
    category: "회계 일반",
    date: "20X3.04",
    title: "수출입 분개관련",
    source: "blog",
    url: "https://hksap.tistory.com/737",
    comment: "수출입 분개 예제가 잘 정리된 외부 참고사이트 모음.",
    configs: [],
    terms: [],
  },
  {
    id: "sk-blog-20",
    category: "회계 일반",
    date: "20X3.03",
    title: "공통매입세액 재계산 관련",
    source: "blog",
    url: "https://hksap.tistory.com/725",
    comment: "면세비율 변동 시 공통매입세액 재계산의 실무 처리 정리. 자산 가감과 비용 처리 중 어느 쪽이 맞는지의 현장 논쟁을 담았다.",
    configs: [],
    terms: [],
  },
  {
    id: "sk-blog-21",
    category: "회계 일반",
    date: "20X2.12",
    title: "유효이자율 관련",
    source: "blog",
    url: "https://hksap.tistory.com/708",
    comment: "상각후원가 금융자산의 유효이자율법 회계처리 참고자료 모음. SAP 처리 방법은 추가 예정인 메모다.",
    configs: [],
    terms: [],
  },
  {
    id: "sk-blog-22",
    category: "회계 일반",
    date: "20X2.01",
    title: "리스회계",
    source: "blog",
    url: "https://hksap.tistory.com/680",
    comment: "리스회계 스터디 자료 모음. 전대·재측정까지 이어지는 학습 타래의 시작점이다.",
    configs: [],
    terms: [],
  },
  {
    id: "sk-blog-23",
    category: "회계 일반",
    date: "20X1.07",
    title: "복구충당부채 회계처리",
    source: "blog",
    url: "https://hksap.tistory.com/651",
    comment: "원상복구 의무가 있는 유형자산의 복구충당부채 회계처리 참고자료 모음.",
    configs: [],
    terms: [],
  },
  {
    id: "sk-blog-24",
    category: "회계 일반",
    date: "20X1.05",
    title: "[연결회계] 투자자본상계 개념",
    source: "blog",
    url: "https://hksap.tistory.com/647",
    comment: "연결재무제표의 투자자본상계 개념 정리. 지분 100% 설립과 지분취득 케이스별 분개 확인용 메모다.",
    configs: [],
    terms: [],
  },
  {
    id: "sk-rxd-553",
    category: "결산·마감",
    date: "20X5.06",
    title: "연평가 후 부분반제 채권 RXD 조정계정 잔액 이슈",
    source: "blog",
    url: "https://hksap.tistory.com/553",
    comment: "외화채권을 여러 차례 부분반제하고 최종 반제했는데 외화평가조정(RXD) 계정 잔액이 0이 되지 않아 현업에서 클레임이 들어온 이슈. 부분반제 시 환차손익 인식 설정이 원인으로 추정돼 개발환경에서 동일 조건으로 재현 테스트해 확인한 기록이다.",
    configs: [],
    terms: [],
  },
  {
    id: "sk-partial-fx-542",
    category: "결산·마감",
    date: "20X5.04",
    title: "외화 부분반제 후 완전반제 시 외화평가조정계정 검증",
    source: "blog",
    url: "https://hksap.tistory.com/542",
    comment: "FAGL_FCV 외화평가 시뮬레이션의 기존차이·신규차이와 외화평가조정계정 누계가 맞지 않는다는 현업 검증 요청에 대한 대응 기록. 부분반제가 여러 채권·채무에 섞여 들어올 때 시뮬레이션 금액과 장부 잔액을 어떻게 대조해야 하는지 정리했다.",
    configs: [],
    terms: [],
  },
  {
    id: "sk-partial-fx-img-526",
    category: "전표·전기",
    date: "20X4.09",
    title: "부분반제 시 환차손익 인식 IMG 위치",
    source: "blog",
    url: "https://hksap.tistory.com/526",
    comment: "부분반제 때 환차손익을 인식하게 하는 IMG 위치를 정리한 메모. 자주 잊어서 남겨 둔 설정 경로 노트로, 외화 부분반제 요건이 있을 때 바로 찾아가는 용도다.",
    configs: [],
    terms: [],
  },
  {
    id: "sk-qty-digits-785",
    category: "전표·전기",
    date: "20X3.09",
    title: "전표입력 시 수량필드 자리 수 관련",
    source: "blog",
    url: "https://hksap.tistory.com/785",
    comment: "전표에 수량 필드를 열어뒀더니 현업에서 99억 개가 넘는 수량을 넣으려다 에러가 난 사례. ACDOCA는 23자리지만 BSEG 수량 필드는 10자리+소수점 3자리라 99억까지만 입력된다. 대량 수량 거래는 단위를 바꿔 관리하기로 협의한 기록이다.",
    configs: [],
    terms: [],
  },
  {
    id: "sk-consol-sol-641",
    category: "회계 일반",
    date: "20X1.04",
    title: "연결회계 솔루션 사례",
    source: "blog",
    url: "https://hksap.tistory.com/641",
    comment: "국내 연결회계 솔루션들을 조사해 정리한 참고자료 모음이다. 각 솔루션의 특징과 관련 자료 링크를 모아둬 연결회계 도입을 검토할 때 꺼내보는 용도다.",
    configs: [],
    terms: [],
  },
  {
    id: "sk-paid-material-442",
    category: "회계 일반",
    date: "",
    title: "유상사급 회계처리",
    source: "blog",
    url: "https://hksap.tistory.com/442",
    comment: "외주 가공을 맡길 때 원재료를 유상으로 넘기는 유상사급의 회계처리를 정리한 글이다. 발주사와 제조회사 양쪽의 분개와 소유권 이전 여부에 따른 처리 차이를 다룬다.",
    configs: [],
    terms: [],
  },
  {
    id: "sk-overseas-subcon-440",
    category: "회계 일반",
    date: "",
    title: "해외임가공 공장",
    source: "blog",
    url: "https://hksap.tistory.com/440",
    comment: "해외 임가공 공장을 거치는 거래의 세금계산서 처리 이슈를 정리한 글이다. 국내 계약인데 생산과 납품이 해외에서 이뤄지면 부가세 없이 면세계산서로 매출과 매입을 주고받는다는 내용과 SD 세금코드 처리 고민이 담겼다.",
    configs: [],
    terms: [],
  },
];
