// 현장 스케치 데이터 — 계속 추가하면서 고도화
// category: 결산·마감 / 전표·전기 / 원가·자재 / 마스터·조직 / MM·SD 연계 / 회계 일반
// date: 20X6.10 형태 (연도 마스킹)
const SKETCHES = [
  {
    id: "sk-wip-mig",
    category: "원가·자재",
    date: "20X4.12",
    title: "시스템 신규 오픈 시 재공품 잔액 Mig 방법",
    source: "blog",
    url: "https://hksap.tistory.com/849",
    comment: "새 시스템 오픈 때 재공품 잔액을 어떻게 옮기느냐는 제조업 FI/CO의 단골 난제다. 방법론이 정해져 있지 않으면 오픈 직전까지도 논쟁이 이어지는 주제라, 미리 정리해 둔 글이 현장에서 바로 써먹힌다.",
    configs: ["co-ml"],
    terms: ["actual-costing", "material-ledger", "wip-accounting"],
  },
  {
    id: "sk-wip-provision",
    category: "원가·자재",
    date: "20X4.09",
    title: "재공품 미실현원가 충당금 관련",
    source: "blog",
    url: "https://hksap.tistory.com/847",
    comment: "재공품에 대한 미실현원가 충당금을 잡아야 하는지, 잡는다면 어느 시점에 잡는지 — 결산 때마다 회계팀과 실랑이하는 주제다. 기준을 정리해 둔 글이 실무 판단에 도움이 된다.",
    configs: ["co-ml"],
    terms: ["actual-costing", "wip-accounting"],
  },
  {
    id: "sk-ml-closing-alloc",
    category: "결산·마감",
    date: "20X4.09",
    title: "자재원장 결산 후 배부하지 않음과 배부되지 않음 관련",
    source: "blog",
    url: "https://hksap.tistory.com/845",
    comment: "자재원장 결산에서 '배부하지 않음'과 '배부되지 않음'은 비슷해 보이지만 원인과 대응이 완전히 다르다. 마감 날 밤에 마주치면 당황하기 쉬운 메시지라 정리 가치가 크다.",
    configs: ["co-alloc", "co-ml"],
    terms: ["actual-costing", "material-ledger-closing"],
  },
  {
    id: "sk-profit-center-segment",
    category: "마스터·조직",
    date: "20X4.09",
    title: "손익센터와 세그먼트 부분",
    source: "blog",
    url: "https://hksap.tistory.com/844",
    comment: "손익센터와 세그먼트는 비슷해 보이지만 용도가 다르다. 전표분할과 함께 이해해야 하는 개념이라 FI 결산 담당자라면 한 번쯤 정리하고 넘어갈 주제다.",
    configs: ["co-prctr", "gl-docsplit"],
    terms: ["document-splitting", "profit-center"],
  },
  {
    id: "sk-real-cost-object",
    category: "원가·자재",
    date: "20X4.07",
    title: "Real Cost Object 관련",
    source: "blog",
    url: "https://hksap.tistory.com/839",
    comment: "실제원가를 계산할 때 기준이 되는 '실원가 대상' 개념. 말은 쉬운데 막상 시스템에서 어디에 매핑되는지 헷갈리는 경우가 많아 정리해 둘 만하다.",
    configs: ["co-ml"],
    terms: ["actual-costing"],
  },
  {
    id: "sk-cost-component",
    category: "원가·자재",
    date: "20X4.06",
    title: "원가구성요소 관련",
    source: "blog",
    url: "https://hksap.tistory.com/832",
    comment: "제품원가를 재료비·노무비·경비로 나누는 원가구성요소. 원가 담당자와 대화할 때 기본이 되는 개념이라 FI 쪽에서도 알아 두면 좋다.",
    configs: ["co-costvar"],
    terms: ["multilevel-costing", "production-costing"],
  },
  {
    id: "sk-copa-topdown",
    category: "결산·마감",
    date: "20X4.06",
    title: "CO-PA 탑다운 배부 관련 자료",
    source: "blog",
    url: "https://hksap.tistory.com/825",
    comment: "CO-PA에서 위에서 아래로 배부하는 탑다운 배부. 수익성분석을 쓰는 현장에서 결산 때마다 돌리는 로직이라 흐름을 알아 두면 좋다.",
    configs: ["co-alloc", "co-margin"],
    terms: ["allocation", "profitability-analysis"],
  },
  {
    id: "sk-internal-order-public",
    category: "마스터·조직",
    date: "20X3.11",
    title: "S/4HANA Cloud Public edition Internal Order관련",
    source: "blog",
    url: "https://hksap.tistory.com/814",
    comment: "Public Edition에서 내부오더가 어떻게 동작하는지 정리한 글. Public은 CO 설정이 제한적이라 되는 것과 안 되는 것을 구분해 두는 게 중요하다.",
    configs: ["co-order"],
    terms: ["internal-order"],
  },
  {
    id: "sk-material-ledger-actual",
    category: "원가·자재",
    date: "20X3.11",
    title: "Material Ledgers/ Actual Costing 관련",
    source: "blog",
    url: "https://hksap.tistory.com/812",
    comment: "자재원장과 실제원가계산의 관계를 정리한 글. 표준원가와 실제원가의 차이가 어디서 발생하는지 이해하는 출발점이다.",
    configs: ["co-ml", "xmod-ml"],
    terms: ["actual-costing", "material-ledger"],
  },
  {
    id: "sk-ml-table",
    category: "원가·자재",
    date: "20X3.07",
    title: "ML Table 관련",
    source: "blog",
    url: "https://hksap.tistory.com/773",
    comment: "자재원장 뒤에 있는 테이블들 정리. 장애나 마감 이슈 때 테이블을 직접 뒤져야 하는 순간이 오는데, 그때 어디를 봐야 하는지 아는 것과 모르는 것의 차이가 크다.",
    configs: ["xmod-ml"],
    terms: ["material-ledger"],
  },
  {
    id: "sk-miro-split",
    category: "MM·SD 연계",
    date: "20X3.02",
    title: "MIRO 송장처리 시 FI전표 분할 관련",
    source: "blog",
    url: "https://hksap.tistory.com/727",
    comment: "MIRO로 송장을 처리할 때 FI 전표가 분할되는 케이스. MM과 FI 경계에서 생기는 이슈라 양쪽 지식이 함께 필요하다.",
    configs: ["close-grir", "gl-docsplit"],
    terms: ["document-splitting", "invoice-verification"],
  },
  {
    id: "sk-reversal-test",
    category: "전표·전기",
    date: "20X3.09",
    title: "역분개전표 역분개 테스트관련",
    source: "blog",
    url: "https://hksap.tistory.com/784",
    comment: "역분개한 전표를 다시 역분개하는 테스트. 말장난 같지만 결산 조정에서 실제로 마주치는 상황이라, 동작 방식을 미리 확인해 두면 실수를 줄일 수 있다.",
    configs: ["gl-reversal-reason"],
    terms: ["reversal"],
  },
  {
    id: "sk-offbook-assets",
    category: "회계 일반",
    date: "",
    title: "장부외자산 1천여 건 생성 및 역분개 처리",
    source: "facebook",
    url: "",
    comment: "장부에 없던 자산 1천여 건을 한 번에 생성하고 역분개까지 처리한 현장 기록. 대량 데이터 처리에서 번호·일자·역분개 사유를 어떻게 통제하는지 보여주는 사례다.",
    configs: ["aa-class", "gl-reversal-reason"],
    terms: ["reversal"],
  },
  {
    id: "sk-card-dup",
    category: "전표·전기",
    date: "",
    title: "법인카드 경비 전표 중복 생성 — 락 오브젝트 통과 사례",
    source: "facebook",
    url: "",
    comment: "법인카드 경비 전표를 두 번 눌러 중복 생성된 사건. 락 오브젝트를 통과해 들어온 케이스로, 인터페이스 전표에서 중복 방지가 왜 중요한지 보여준다.",
    configs: ["gl-doc-type"],
    terms: ["document"],
  },
  {
    id: "sk-wip-actual-public",
    category: "회계 일반",
    date: "",
    title: "WIP at Actual — Public에서 전표 나온 날",
    source: "facebook",
    url: "",
    comment: "Public Edition에서 WIP at Actual로 전표가 처음 나온 날의 기록. Public에서 CO가 돌아간다는 것 자체가 관심사라 현장감이 있다.",
    configs: ["co-ml"],
    terms: ["actual-costing", "wip-accounting"],
  },
  {
    id: "sk-co-settle-mismatch",
    category: "회계 일반",
    date: "",
    title: "CO 결산 검증 — 타계정이 원계정 안 따라감",
    source: "facebook",
    url: "",
    comment: "CO 결산 검증 중 타계정이 원계정을 따라가지 않은 이슈. 배부·분배 로직에서 계정 매핑이 어긋나면 생기는 전형적인 결산 트러블이다.",
    configs: ["co-alloc", "co-close"],
    terms: ["allocation"],
  },
  {
    id: "sk-first-close",
    category: "결산·마감",
    date: "",
    title: "오픈 후 첫 결산 드디어 끝",
    source: "facebook",
    url: "",
    comment: "시스템 오픈 후 첫 결산을 마친 날의 기록. 오픈 첫 달 결산이 왜 힘든지 겪어본 사람만 아는 감정이 담겨 있다.",
    configs: ["close-cockpit"],
    terms: ["closing-cockpit"],
  },
  {
    id: "sk-gl-ml-mismatch",
    category: "회계 일반",
    date: "",
    title: "FI G/L 잔액 vs CO-ML 금액 불일치 — OSS 재등록",
    source: "evernote",
    url: "",
    comment: "운영 시스템에서 FI G/L 잔액과 CO 자재원장 금액이 맞지 않아 OSS에 재등록 요청한 사례. FI와 CO가 어긋나는 순간이 왜 생기는지 보여주는 트러블슈팅 기록이다.",
    configs: ["co-ml", "xmod-ml"],
    terms: ["actual-costing", "material-ledger"],
  },
  {
    id: "sk-overseas-go-live-close",
    category: "회계 일반",
    date: "",
    title: "해외법인 오픈 후 첫 월결산 — FI/CO 일치로 마감",
    source: "evernote",
    url: "",
    comment: "해외법인 오픈 후 8월 결산을 물류 D+2, 재무/원가 D+6에 FI/CO 일치로 마친 기록. 결산 스케줄이 현장에서 어떻게 돌아가는지 보여주는 사례다.",
    configs: ["close-cockpit"],
    terms: ["closing-cockpit"],
  },
  {
    id: "sk-lines-999",
    category: "전표·전기",
    date: "",
    title: "999라인 넘는 전표",
    source: "keep",
    url: "",
    comment: "한 전표에 999라인이 넘는 경우에 대한 메모. 대량 라인 전표는 성능·번호·출력에서 별도 고려가 필요해 현장에서 자주 화젯거리가 된다. S/4 자산취득·매각은 거래전표와 평가전표가 고정자산기술적임시계정으로 분리돼 2차전표가 생기는데, 자산 1건당 2라인이 생겨 거래전표 499라인까지만 가능하고 500라인부터는 999라인을 초과해 에러가 난다.",
    links: [
      { type: "blog", title: "[AA] 자산취득 및 매각 2차전표 관련", url: "https://hksap.tistory.com/786" }
    ],
    configs: ["gl-doc-type", "aa-acctdet"],
    terms: ["document", "line-item"],
  },
  {
    id: "sk-blog-01",
    category: "전표·전기",
    date: "20X5.05",
    title: "전표입력 Fiori 앱에서 그룹통화 변경",
    source: "blog",
    url: "https://hksap.tistory.com/861",
    comment: "Fiori 전표 입력에서 그룹통화 금액을 바꾸는 방법을 정리한 글이다. GUI와 Fiori 앱의 동작이 달라 현장에서 헷갈리기 쉬운 지점이다.",
    configs: ["gl-global-param"],
    terms: ["document-currency", "local-currency"],
  },
  {
    id: "sk-blog-02",
    category: "전표·전기",
    date: "20X5.05",
    title: "SPGL 관련",
    source: "blog",
    url: "https://hksap.tistory.com/860",
    comment: "특별 G/L(SPGL)이 무엇인지, 왜 쓰는지를 정리한 참고자료다. 선수금·어음 같은 보조부 관리 대상을 이해하는 데 도움이 된다.",
    configs: [],
    terms: ["special-gl-indicator", "special-gl-account"],
  },
  {
    id: "sk-blog-03",
    category: "전표·전기",
    date: "",
    title: "전기일 <> 반제일 Case",
    source: "blog",
    url: "https://hksap.tistory.com/848",
    comment: "반제일은 전기일보다 먼저일 수 없다는 SAP 기본 규칙을 다룬 글. 반제 전표 처리 시 날짜 오류가 나면 가장 먼저 의심해볼 포인트다.",
    configs: ["gl-reversal-reason"],
    terms: ["reversal", "document-date"],
  },
  {
    id: "sk-blog-04",
    category: "전표·전기",
    date: "20X4.07",
    title: "F110 자동지급 처리 시 지급전표 필드 대체룰 처리 관련",
    source: "blog",
    url: "https://hksap.tistory.com/841",
    comment: "F110 지급전표의 참조 필드를 대체룰로 채우는 고객 요건을 정리한 글. ECC와 S/4HANA의 차이, 디버깅 참고자료를 함께 모았다.",
    configs: ["gl-substitution", "ap-paymethod-ccode"],
    terms: ["automatic-payment", "substitution"],
  },
  {
    id: "sk-blog-05",
    category: "결산·마감",
    date: "20X4.07",
    title: "F.19 GR/IR 미착대체 관련",
    source: "blog",
    url: "https://hksap.tistory.com/834",
    comment: "결산 때마다 나오는 GR/IR 미착·미지급비용 대체를 F.19로 처리하는 방법 정리. T-Code를 잊기 쉬워 메모해 둔 실무 치트시트다.",
    configs: ["close-grir"],
    terms: ["gr-ir"],
  },
  {
    id: "sk-blog-06",
    category: "전표·전기",
    date: "20X4.06",
    title: "F5080 Consolidated companies XXXX and ' ' are different",
    source: "blog",
    url: "https://hksap.tistory.com/831",
    comment: "관계사 BP와 일반 거래처가 한 전표에 섞이면 나는 F5080 에러와, 전표유형의 회사간거래 체크로 해결한 기록.",
    configs: ["xmod-interco"],
    terms: ["intercompany"],
  },
  {
    id: "sk-blog-07",
    category: "전표·전기",
    date: "20X4.04",
    title: "AR & AP 일괄 F110 처리 관련",
    source: "blog",
    url: "https://hksap.tistory.com/821",
    comment: "F110으로 AR 입금·AP 지급·상계까지 한 번에 처리한 테스트 기록. 마스터의 반제 허용 체크가 핵심 포인트다.",
    configs: ["ap-paymethod-ccode", "ap-recon", "ar-recon"],
    terms: ["automatic-payment", "clearing"],
  },
  {
    id: "sk-blog-08",
    category: "마스터·조직",
    date: "20X4.02",
    title: "건설중인자산 mig시 전기일 관련",
    source: "blog",
    url: "https://hksap.tistory.com/820",
    comment: "건설중인자산 이관 시 거래유형 100은 이관일, 900은 1월 1일로 들어가는 SAP 표준 규칙 정리. 현업 클레임 대응용 근거 메모다.",
    configs: ["aa-transtype", "co-auc-settle"],
    terms: ["acquire-to-decommission"],
  },
  {
    id: "sk-blog-09",
    category: "원가·자재",
    date: "20X5.01",
    title: "표준원가 추정시 외자 적용 환율 관련",
    source: "blog",
    url: "https://hksap.tistory.com/857",
    comment: "표준원가 추정 때 외자에 P타입 환율만 넣으면 에러가 나고 M타입까지 넣어야 통과됐던 사례다. 추정 직전 체크리스트로 쓸 만하다.",
    configs: ["co-costvar"],
    terms: ["standard-cost-valuation", "foreign-currency-valuation"],
  },
  {
    id: "sk-blog-10",
    category: "MM·SD 연계",
    date: "20X5.01",
    title: "MM 입고시 회계전표 안나오게 설정",
    source: "blog",
    url: "https://hksap.tistory.com/856",
    comment: "MM 입고 시점에 회계전표가 안 나오게 하고 송장 시점에 처리하는 설정 방법을 정리했다. GR/IR 없이 가는 요건에서 쓴다.",
    configs: ["xmod-obyc"],
    terms: ["gr-ir", "invoice-verification"],
  },
  {
    id: "sk-blog-11",
    category: "MM·SD 연계",
    date: "20X5.01",
    title: "OBYC GBB-VAX GBB-VAY 관련",
    source: "blog",
    url: "https://hksap.tistory.com/855",
    comment: "OBYC의 GBB-VAX/VAY가 언제 어느 계정으로 빠지는지 정리한 글이다. 매출원가 계정 결정의 기본기라 MM-FI 연계의 출발점이다.",
    configs: ["xmod-obyc"],
    terms: ["obyc", "gbb"],
  },
  {
    id: "sk-blog-12",
    category: "원가·자재",
    date: "20X4.12",
    title: "외주생산시 제품 입고시점 제조간접부서의 경비 처리 관련",
    source: "blog",
    url: "https://hksap.tistory.com/854",
    comment: "외주생산으로 제품이 입고될 때 제조간접부서의 재료비·노무비·경비를 어떻게 처리할지 정리한 글이다. 자체 생산라인이 없는 구조에서 꼭 마주치는 주제다.",
    configs: ["co-costvar", "xmod-obyc"],
    terms: ["production-costing", "overhead-calculation"],
  },
  {
    id: "sk-blog-13",
    category: "원가·자재",
    date: "20X4.12",
    title: "부산물의 실제원가 관련",
    source: "blog",
    url: "https://hksap.tistory.com/853",
    comment: "부산물의 실제원가를 어떻게 구하는지 정리한 글이다. BOM에 마이너스로 달고 순실현가치로 추정하는 실무 팁이 담겼다.",
    configs: ["co-costvar", "co-ml"],
    terms: ["by-product-accounting", "actual-costing"],
  },
  {
    id: "sk-blog-14",
    category: "원가·자재",
    date: "20X4.12",
    title: "수입자재 표준원가 추정 관련",
    source: "blog",
    url: "https://hksap.tistory.com/852",
    comment: "수입자재 표준원가에 부대비까지 반영해 추정하는 방법을 정리했다. 코스트시트를 쓰는 실무 접근이 담겼다.",
    configs: ["co-costvar"],
    terms: ["standard-cost-valuation", "production-costing"],
  },
  {
    id: "sk-blog-15",
    category: "원가·자재",
    date: "20X4.12",
    title: "반제품을 구매시 처리방법 관련",
    source: "blog",
    url: "https://hksap.tistory.com/851",
    comment: "구매와 생산이 섞인 반제품을 RoH/HALB 중 어떻게 분류할지, 평가유형 분리의 실무 논쟁을 정리한 글.",
    configs: ["co-costvar"],
    terms: ["material-master", "production-costing"],
  },
  {
    id: "sk-blog-16",
    category: "원가·자재",
    date: "20X4.12",
    title: "공정중 불량 처리방법 관련",
    source: "blog",
    url: "https://hksap.tistory.com/850",
    comment: "공정 중 불량은 재료비 투입을 취소하고 가공비만 남겨 TECO·정산하는 가이드. CO/PP 현장의 단골 질문이다.",
    configs: ["co-costvar", "co-order"],
    terms: ["production-costing", "production-variance-analysis"],
  },
  {
    id: "sk-blog-17",
    category: "회계 일반",
    date: "",
    title: "연결회계 관련 참고자료",
    source: "blog",
    url: "https://hksap.tistory.com/826",
    comment: "지분법과 연결회계가 본질적으로 같다는 외부 칼럼 소개. 그룹리포팅 프로젝트 준비용 스터디 메모다.",
    configs: [],
    terms: ["consolidation"],
  },
  {
    id: "sk-blog-18",
    category: "회계 일반",
    date: "20X3.03",
    title: "리스채권과 투자부동산관련",
    source: "blog",
    url: "https://hksap.tistory.com/741",
    comment: "IFRS 16 리스채권과 IAS 40 투자부동산의 구분을 정리한 글. SAP 표준 리스 회계 적용 방안을 논의한 메모다.",
    configs: [],
    terms: ["lease-accounting", "right-of-use-asset"],
  },
  {
    id: "sk-blog-19",
    category: "회계 일반",
    date: "20X3.04",
    title: "수출입 분개관련",
    source: "blog",
    url: "https://hksap.tistory.com/737",
    comment: "수출입 분개 예제가 잘 정리된 외부 참고사이트 모음.",
    configs: ["gl-doc-type"],
    terms: ["document", "foreign-currency-valuation"],
  },
  {
    id: "sk-blog-20",
    category: "회계 일반",
    date: "20X3.03",
    title: "공통매입세액 재계산 관련",
    source: "blog",
    url: "https://hksap.tistory.com/725",
    comment: "면세비율 변동 시 공통매입세액 재계산의 실무 처리 정리. 자산 가감과 비용 처리 중 어느 쪽이 맞는지의 현장 논쟁을 담았다.",
    configs: ["tax-code", "tax-account"],
    terms: ["tax-code"],
  },
  {
    id: "sk-blog-21",
    category: "회계 일반",
    date: "20X2.12",
    title: "유효이자율 관련",
    source: "blog",
    url: "https://hksap.tistory.com/708",
    comment: "상각후원가 금융자산의 유효이자율법 회계처리 참고자료 모음. SAP 처리 방법은 추가 예정인 메모다.",
    configs: ["close-accrual"],
    terms: ["accrual-engine"],
  },
  {
    id: "sk-blog-22",
    category: "회계 일반",
    date: "20X2.01",
    title: "리스회계",
    source: "blog",
    url: "https://hksap.tistory.com/680",
    comment: "리스회계 스터디 자료 모음. 전대·재측정까지 이어지는 학습 타래의 시작점이다.",
    configs: [],
    terms: ["lease-accounting", "right-of-use-asset"],
  },
  {
    id: "sk-blog-23",
    category: "회계 일반",
    date: "20X1.07",
    title: "복구충당부채 회계처리",
    source: "blog",
    url: "https://hksap.tistory.com/651",
    comment: "원상복구 의무가 있는 유형자산의 복구충당부채 회계처리 참고자료 모음.",
    configs: ["aa-acctdet"],
    terms: ["asset-retirement"],
  },
  {
    id: "sk-blog-24",
    category: "회계 일반",
    date: "20X1.05",
    title: "[연결회계] 투자자본상계 개념",
    source: "blog",
    url: "https://hksap.tistory.com/647",
    comment: "연결재무제표의 투자자본상계 개념 정리. 지분 100% 설립과 지분취득 케이스별 분개 확인용 메모다.",
    configs: [],
    terms: ["consolidation", "consolidation-adjustment", "intercompany-elimination"],
  },
  {
    id: "sk-rxd-553",
    category: "결산·마감",
    date: "20X5.06",
    title: "연평가 후 부분반제 채권 RXD 조정계정 잔액 이슈",
    source: "blog",
    url: "https://hksap.tistory.com/553",
    comment: "외화채권을 여러 차례 부분반제하고 최종 반제했는데 외화평가조정(RXD) 계정 잔액이 0이 되지 않아 현업에서 클레임이 들어온 이슈. 부분반제 시 환차손익 인식 설정이 원인으로 추정돼 개발환경에서 동일 조건으로 재현 테스트해 확인한 기록이다.",
    configs: ["close-fxval", "gl-fx-diff-acct"],
    terms: ["foreign-currency-valuation", "partial-payment"],
  },
  {
    id: "sk-partial-fx-542",
    category: "결산·마감",
    date: "20X5.04",
    title: "외화 부분반제 후 완전반제 시 외화평가조정계정 검증",
    source: "blog",
    url: "https://hksap.tistory.com/542",
    comment: "FAGL_FCV 외화평가 시뮬레이션의 기존차이·신규차이와 외화평가조정계정 누계가 맞지 않는다는 현업 검증 요청에 대한 대응 기록. 부분반제가 여러 채권·채무에 섞여 들어올 때 시뮬레이션 금액과 장부 잔액을 어떻게 대조해야 하는지 정리했다.",
    configs: ["close-fxval", "gl-fx-diff-acct"],
    terms: ["foreign-currency-valuation", "partial-payment"],
  },
  {
    id: "sk-partial-fx-img-526",
    category: "전표·전기",
    date: "20X4.09",
    title: "부분반제 시 환차손익 인식 IMG 위치",
    source: "blog",
    url: "https://hksap.tistory.com/526",
    comment: "부분반제 때 환차손익을 인식하게 하는 IMG 위치를 정리한 메모. 자주 잊어서 남겨 둔 설정 경로 노트로, 외화 부분반제 요건이 있을 때 바로 찾아가는 용도다.",
    configs: ["close-fxval", "gl-fx-diff-acct"],
    terms: ["foreign-currency-valuation", "partial-payment"],
  },
  {
    id: "sk-qty-digits-785",
    category: "전표·전기",
    date: "20X3.09",
    title: "전표입력 시 수량필드 자리 수 관련",
    source: "blog",
    url: "https://hksap.tistory.com/785",
    comment: "전표에 수량 필드를 열어뒀더니 현업에서 99억 개가 넘는 수량을 넣으려다 에러가 난 사례. ACDOCA는 23자리지만 BSEG 수량 필드는 10자리+소수점 3자리라 99억까지만 입력된다. 대량 수량 거래는 단위를 바꿔 관리하기로 협의한 기록이다.",
    configs: ["gl-field-status"],
    terms: ["field-status", "document", "line-item"],
  },
  {
    id: "sk-consol-sol-641",
    category: "회계 일반",
    date: "20X1.04",
    title: "연결회계 솔루션 사례",
    source: "blog",
    url: "https://hksap.tistory.com/641",
    comment: "국내 연결회계 솔루션들을 조사해 정리한 참고자료 모음이다. 각 솔루션의 특징과 관련 자료 링크를 모아둬 연결회계 도입을 검토할 때 꺼내보는 용도다.",
    configs: [],
    terms: ["consolidation"],
  },
  {
    id: "sk-paid-material-442",
    category: "회계 일반",
    date: "",
    title: "유상사급 회계처리",
    source: "blog",
    url: "https://hksap.tistory.com/442",
    comment: "외주 가공을 맡길 때 원재료를 유상으로 넘기는 유상사급의 회계처리를 정리한 글이다. 발주사와 제조회사 양쪽의 분개와 소유권 이전 여부에 따른 처리 차이를 다룬다.",
    configs: ["xmod-obyc"],
    terms: ["inventory-accounting"],
  },
  {
    id: "sk-overseas-subcon-440",
    category: "회계 일반",
    date: "",
    title: "해외임가공 공장",
    source: "blog",
    url: "https://hksap.tistory.com/440",
    comment: "해외 임가공 공장을 거치는 거래의 세금계산서 처리 이슈를 정리한 글이다. 국내 계약인데 생산과 납품이 해외에서 이뤄지면 부가세 없이 면세계산서로 매출과 매입을 주고받는다는 내용과 SD 세금코드 처리 고민이 담겼다.",
    configs: ["tax-code", "xmod-sdbill"],
    terms: ["tax-code"],
  },
  {
    id: "sk-closing-checklist-390",
    category: "결산·마감",
    date: "20X9.07",
    title: "결산체크리스트",
    source: "blog",
    url: "https://hksap.tistory.com/390",
    comment: "자산·부채·자본·손익 항목별로 결산 때 점검해야 할 사항을 정리한 체크리스트다. 계정잔액 대조부터 세무조정까지 항목별로 스스로 물어보는 형태로 되어 있다.",
    configs: ["close-cockpit"],
    terms: ["closing-cockpit", "closing-monitor"],
  },
  {
    id: "sk-etax-388",
    category: "회계 일반",
    date: "20X9.06",
    title: "전자세금계산서 그리고 전자어음 의무화 시행",
    source: "blog",
    url: "https://hksap.tistory.com/388",
    comment: "전자세금계산서와 전자어음 의무화 시행 시점에 SAP 인터페이스 고민을 정리한 글이다. 매출은 ASP로 밀어 넣으면 되지만 중견기업의 역발행 매입세금계산서 국세청 신고 처리가 고민거리로 남았다는 내용이다.",
    configs: ["tax-code"],
    terms: ["tax-code", "document"],
  },
  {
    id: "sk-material-subcon-184",
    category: "회계 일반",
    date: "20X3.05",
    title: "원자재 사급관련 회계처리 Case Study",
    source: "blog",
    url: "https://hksap.tistory.com/184",
    comment: "원자재 사급의 회계처리를 유상사급과 무상사급으로 나눠 정리한 케이스 스터디다. SAP에서는 MM 물류전표와 생산오더, SD 빌링으로 어떻게 접근할지 고민한 기록이다.",
    configs: ["xmod-obyc"],
    terms: ["inventory-accounting", "production-costing"],
  },
  {
    id: "sk-apc-797",
    category: "결산·마감",
    date: "20X3.10",
    title: "자산 APC 뜻 관련",
    source: "blog",
    url: "https://hksap.tistory.com/797",
    comment: "오픈 후 첫 결산에서 에피소드가 생기며 자산 APC의 뜻을 찾아본 기록이다. APC는 Acquisition and Production costs의 약자로 취득·생산원가를 의미한다.",
    configs: ["aa-acctdet"],
    terms: ["acquire-to-decommission"],
  },
  {
    id: "sk-accrual-mig-548",
    category: "결산·마감",
    date: "20X5.05",
    title: "Accrual engine migration 대량 등록시 처리부분",
    source: "blog",
    url: "https://hksap.tistory.com/548",
    comment: "장기 선급비용 100여 건을 Accrual Engine으로 마이그레이션하면서 건별 처리가 부담돼 BDC 녹화로 대량 등록한 기록이다.",
    configs: ["close-accrual"],
    terms: ["accrual-engine"],
  },  {
    id: "sk-auc-settle-745",
    category: "결산·마감",
    date: "20X3.03",
    title: "건설중인자산 투자오더 정산관련",
    source: "blog",
    url: "https://hksap.tistory.com/745",
    comment: "건설중인자산을 투자오더로 취득했을 때 AIAB가 아닌 KO8G에서 투자오더를 정산해야 본자산으로 대체된다는 점을 정리한 글이다.",
    configs: ["co-auc-settle", "aa-settlement"],
    terms: ["acquire-to-decommission"],
  },
  {
    id: "sk-aa-techclear-799",
    category: "결산·마감",
    date: "20X3.09",
    title: "고정자산 기술적임시계정 관련",
    source: "blog",
    url: "https://hksap.tistory.com/799",
    comment: "신규 S/4HANA에서 자산전표가 2개로 나뉘는 이유를 설명한 기록이다. 예전 ECC처럼 한 전표로 처리할 수 없는지 묻는 현업 질의에 대한 답변용 메모다.",
    configs: ["aa-acctdet"],
    terms: ["acquire-to-decommission"],
  },
  {
    id: "sk-f5702-770",
    category: "전표·전기",
    date: "20X3.06",
    title: "전표저장시 F5702 거래통화잔액 에러 관련",
    source: "blog",
    url: "https://hksap.tistory.com/770",
    comment: "회사코드 통화와 전표 통화가 같은데도 환율 0이라며 F5702 에러로 전표가 저장되지 않던 현상의 원인 추적 기록이다. 이관된 대체룰이 의심 대상으로 지목됐다.",
    configs: ["gl-substitution"],
    terms: ["document-currency", "local-currency", "substitution"],
  },
  {
    id: "sk-f05-local-543",
    category: "전표·전기",
    date: "20X5.04",
    title: "F-05 사용시 Local currency amount '0'인건 관련",
    source: "blog",
    url: "https://hksap.tistory.com/543",
    comment: "마이그레이션 전 환차손익 전표를 넣기 위해 F-05 외화평가를 썼는데 전표통화 금액만 넣으면 자동으로 계산되지 않던 이슈를 다룬 글이다.",
    configs: ["close-fxval"],
    terms: ["foreign-currency-valuation", "document-currency"],
  },
  {
    id: "sk-openitem-field-77",
    category: "전표·전기",
    date: "20X7.03",
    title: "포스팅된 Open Item의 필드상태를 IMG에서 조정",
    source: "blog",
    url: "https://hksap.tistory.com/77",
    comment: "이미 전기된 미결항목의 필드상태를 IMG에서 조정하는 방법을 정리한 프로젝트 안정화 단계의 메모다.",
    configs: ["gl-field-status"],
    terms: ["field-status", "open-item-management"],
  },
  {
    id: "sk-negposting-251",
    category: "전표·전기",
    date: "20X7.12",
    title: "마이너스전기허용",
    source: "blog",
    url: "https://hksap.tistory.com/251",
    comment: "음의전기 허용 설정의 IMG 경로를 정리한 메모다. 전표유형 정의, 광역매개변수, 음의전기 허용 세 군데를 순서대로 다룬다.",
    configs: ["gl-negative-posting"],
    terms: ["negative-posting", "document-type"],
  },
  {
    id: "sk-autoposting-456",
    category: "전표·전기",
    date: "20X3.05",
    title: "Autoposting",
    source: "blog",
    url: "https://hksap.tistory.com/456",
    comment: "MM 자동전기와 가격차이 계정 관련 참고자료 모음이다. BSV 재고변경계정과 무상사급 자재의 입고·반품 시 상대계정 정리가 담겼다.",
    configs: ["xmod-obyc"],
    terms: ["obyc"],
  },
  {
    id: "sk-ws-doctype-597",
    category: "전표·전기",
    date: "20X8.01",
    title: "구매계정 설정후 WS전표유형 관련 설정",
    source: "blog",
    url: "https://hksap.tistory.com/597",
    comment: "송장 취소(MR8M) 시 WS 전표유형으로 표준 설정되는 것을 OMR4에서 공란으로 바꿔 해결한 기록이다. 구매계정 관리 참고자료도 함께 모았다.",
    configs: ["gl-doc-type", "xmod-obyc"],
    terms: ["document-type"],
  },
  {
    id: "sk-faa-post042-792",
    category: "전표·전기",
    date: "20X3.09",
    title: "FAA_POST042 Balance in Technical Clearing",
    source: "blog",
    url: "https://hksap.tistory.com/792",
    comment: "개발서버에서 되던 자산전표가 운영에서 FAA_POST042 기술적임시계정 잔액 에러로 막힌 현상의 원인 추적 기록이다.",
    configs: ["aa-acctdet"],
    terms: ["acquire-to-decommission"],
  },
  {
    id: "sk-bapi-arev-744",
    category: "전표·전기",
    date: "20X3.03",
    title: "BAPI_ASSET_REVERSAL_POST 관련",
    source: "blog",
    url: "https://hksap.tistory.com/744",
    comment: "마이그레이션 테스트 자산의 금액 오류를 AB08 BDC 대신 자산취소 BAPI로 처리할 수 있는지 찾아본 메모다.",
    configs: ["gl-reversal-reason"],
    terms: ["reversal"],
  },  {
    id: "sk-inv-price-762",
    category: "원가·자재",
    date: "20X3.05",
    title: "재고단가관련",
    source: "blog",
    url: "https://hksap.tistory.com/762",
    comment: "이동평균가와 표준원가의 차이를 정리한 외부 참고자료다. 재고 단가 방식을 이해하는 데 쓰는 메모다.",
    configs: ["co-ml"],
    terms: ["standard-cost-valuation", "actual-costing"],
  },
  {
    id: "sk-mr21-775",
    category: "원가·자재",
    date: "20X3.07",
    title: "MR21 / MR22 관련",
    source: "blog",
    url: "https://hksap.tistory.com/775",
    comment: "자재마스터의 이동평균가나 재고금액을 바꿀 때 쓰는 MR21·MR22와 사유별 OBYC UMB 이원화 구성을 정리한 글이다.",
    configs: ["xmod-obyc"],
    terms: ["standard-cost-valuation", "price-variance"],
  },
  {
    id: "sk-extprocess-705",
    category: "원가·자재",
    date: "20X2.12",
    title: "공정중 외주관련 external process",
    source: "blog",
    url: "https://hksap.tistory.com/705",
    comment: "공정 중 외주 프로세스에서 당월 마감일까지 실물 인보이스 없이 송장처리를 해야 하는 업무상 어려움을 정리한 글이다.",
    configs: ["co-order"],
    terms: ["production-costing"],
  },
  {
    id: "sk-nonvaluated-509",
    category: "원가·자재",
    date: "20X4.07",
    title: "비평가자재 관련",
    source: "blog",
    url: "https://hksap.tistory.com/509",
    comment: "무상사급으로 받아오는 비평가자재의 표준원가 0원 허용 문제를 다룬 QnA 정리다. 하위 반제품부터 완제품까지 에러가 전파되는 구조를 설명한다.",
    configs: ["co-costvar"],
    terms: ["material-master", "production-costing"],
  },
  {
    id: "sk-pricectrl-v-516",
    category: "원가·자재",
    date: "20X4.07",
    title: "Price control V 일때 구매입고 가격차이전표",
    source: "blog",
    url: "https://hksap.tistory.com/516",
    comment: "가격결정 V인 자재의 구매입고 때 MAP와 내부표준원가 차이가 가격차이로 떨어지며 전표가 두 장으로 나뉘는 구조를 정리한 글이다.",
    configs: ["xmod-obyc", "co-ml"],
    terms: ["price-variance", "actual-costing"],
  },
  {
    id: "sk-co-depplan-696",
    category: "원가·자재",
    date: "20X2.10",
    title: "CO 계획 감가상각비 관련",
    source: "blog",
    url: "https://hksap.tistory.com/696",
    comment: "자산별 상각비가 해당 원가요소와 코스트센터 계획값에 반영되는 CO 리포트(S_ALR_87099918) 참고자료다.",
    configs: ["co-ccenter"],
    terms: ["cost-center-accounting"],
  },
  {
    id: "sk-bp-role-819",
    category: "마스터·조직",
    date: "20X4.01",
    title: "BP 역할 관련",
    source: "blog",
    url: "https://hksap.tistory.com/819",
    comment: "BP 역할이 예전 ECC의 고객·공급처 계정그룹과 유사한 개념인지 찾아본 메모다. 역할에 유효기간 관리도 가능하다는 점이 담겼다.",
    configs: ["ap-bp-role"],
    terms: ["business-partner", "cvi"],
  },
  {
    id: "sk-newledger-606",
    category: "마스터·조직",
    date: "20X9.03",
    title: "신규회계기준 원장추가하여 오픈",
    source: "blog",
    url: "https://hksap.tistory.com/606",
    comment: "신규 회계기준 적용으로 원장그룹과 원장 3건을 기중에 추가해 오픈한 기록이다. 코딩블록 필드 추가가 아니라 금방 운영에 반영됐다는 메모다.",
    configs: ["gl-ledger", "gl-acct-principle"],
    terms: ["ledger", "ledger-group"],
  },
  {
    id: "sk-codingblock-808",
    category: "마스터·조직",
    date: "20X3.11",
    title: "Coding Block 사용자필드 추가관련",
    source: "blog",
    url: "https://hksap.tistory.com/808",
    comment: "ACDOCA 원장에 사용자필드를 추가하는 Coding Block 확장 방법을 정리한 참고자료다.",
    configs: [],
    terms: ["additional-account-assignment"],
  },
  {
    id: "sk-fsv-811",
    category: "마스터·조직",
    date: "20X3.11",
    title: "재무제표(FSV) 버전관련",
    source: "blog",
    url: "https://hksap.tistory.com/811",
    comment: "프로젝트에서 정책적으로 재무제표 버전을 쓰지 않기로 한 배경과 자산 쪽 표준리포트 사용 현황을 정리한 메모다.",
    configs: ["gl-fsver"],
    terms: ["fs-version"],
  },
  {
    id: "sk-bankgl-n1-822",
    category: "마스터·조직",
    date: "20X4.04",
    title: "은행계좌 G/L계정관리 관련 (N:1)",
    source: "blog",
    url: "https://hksap.tistory.com/822",
    comment: "은행 GL 계정 1개만 쓰고 계좌를 관리항목으로 등록할 수 없는지 묻는 현업 질의에 대한 조사 메모다. 손익센터 자동지정과 외화통장 환산손익 추가 관리가 포인트다.",
    configs: ["bank-glstruct"],
    terms: ["house-bank"],
  },
  {
    id: "sk-bankdigit-496",
    category: "마스터·조직",
    date: "20X4.02",
    title: "Bank account digit 관련",
    source: "blog",
    url: "https://hksap.tistory.com/496",
    comment: "은행계좌 등록 시 18자리를 넘는 해외 거래처 계좌를 어떻게 처리하는지에 대한 QnA 정리다.",
    configs: ["bank-master"],
    terms: ["bank-master"],
  },
  {
    id: "sk-wl-asset-809",
    category: "마스터·조직",
    date: "20X3.11",
    title: "WL을 이용한 고정자산 대량처리 부분",
    source: "blog",
    url: "https://hksap.tistory.com/809",
    comment: "고정자산 이관·매각·폐기를 WorkList로 대량 처리하던 중견회사 시절 방식을 정리한 글이다. 대형 프로젝트의 CBO 방식과 대비되는 메모다.",
    configs: ["aa-class"],
    terms: ["asset-class"],
  },
  {
    id: "sk-ledger-prod-818",
    category: "마스터·조직",
    date: "20X4.01",
    title: "운영 환경에서 회계원장 추가관련",
    source: "blog",
    url: "https://hksap.tistory.com/818",
    comment: "운영 환경에서 원장을 추가할 때 기존 총계 테이블 금액이 신규원장으로 복사되는지 정리한 메모다. FAGL_FLEXA 기준 복사 트랜잭션이 담겼다.",
    configs: ["gl-ledger"],
    terms: ["ledger"],
  },
  {
    id: "sk-fiscvar-676",
    category: "마스터·조직",
    date: "20X1.10",
    title: "회계연도 변형관련",
    source: "blog",
    url: "https://hksap.tistory.com/676",
    comment: "회계연도와 회계연도 변형 설명자료 모음이다. 2월 결산법인의 1기(3월~) 설정 사례가 담겼다.",
    configs: ["gl-fiscal-year"],
    terms: ["fiscal-year-variant"],
  },
  {
    id: "sk-period-mgmt-662",
    category: "마스터·조직",
    date: "20X1.09",
    title: "전기기간 관리 관련",
    source: "blog",
    url: "https://hksap.tistory.com/662",
    comment: "FI·CO·물류 전기기간 관리 참고자료 모음이다. OB52, OKP1, MMPV/MMRV와 권한 오브젝트 매핑 설명이 담겼다.",
    configs: ["gl-posting-period"],
    terms: ["posting-period"],
  },
  {
    id: "sk-prctr-807",
    category: "마스터·조직",
    date: "20X3.11",
    title: "Profit center관련",
    source: "blog",
    url: "https://hksap.tistory.com/807",
    comment: "손익센터가 Cost Object인 줄 알았는데 아니었다는 학습 메모다. 지원부서도 코스트센터와 1:1로 손익센터를 만든 현장 사례가 담겼다.",
    configs: ["co-prctr"],
    terms: ["profit-center"],
  },  {
    id: "sk-co-numrange-294",
    category: "마스터·조직",
    date: "20X8.02",
    title: "CO번호범위 에러",
    source: "blog",
    url: "https://hksap.tistory.com/294",
    comment: "CO 번호범위를 삭제하려다 오브젝트가 조회되지 않아 막힌 경우의 해결책을 정리한 글이다.",
    configs: [],
    terms: ["number-range"],
  },
  {
    id: "sk-aa269-763",
    category: "마스터·조직",
    date: "20X3.05",
    title: "AA269 번호범위 warning area 메세지관련",
    source: "blog",
    url: "https://hksap.tistory.com/763",
    comment: "자산 번호범위가 경고 영역에 도달했다는 AA269 메시지의 원인을 정리한 메모다.",
    configs: ["aa-numrange"],
    terms: ["number-range"],
  },
  {
    id: "sk-costcenter-415",
    category: "마스터·조직",
    date: "20X2.01",
    title: "Missing cost center while posting asset",
    source: "blog",
    url: "https://hksap.tistory.com/415",
    comment: "고정자산 취득 시 코스트센터가 보이지 않던 현상의 해결 기록이다. 추가계정지정 활성화와 계정지정유형 등록, 필드상태 점검이 순서대로 담겼다.",
    configs: ["co-ccenter"],
    terms: ["cost-center"],
  },
  {
    id: "sk-periodpl-337",
    category: "마스터·조직",
    date: "20X8.10",
    title: "기간손익설정 (Configuration)",
    source: "blog",
    url: "https://hksap.tistory.com/337",
    comment: "기간손익 인식(수동)의 IMG 경로를 정리한 설정 메모다. 회사코드 지정부터 발생 유형 정의까지 순서가 담겼다.",
    configs: ["close-accrual"],
    terms: ["accrual-engine"],
  },
  {
    id: "sk-pa-qa-674",
    category: "MM·SD 연계",
    date: "20X1.10",
    title: "MM, FI, CO 모듈만 사용시 매출원가 PA처리관련 QA",
    source: "blog",
    url: "https://hksap.tistory.com/674",
    comment: "PP·SD 없이 MM·FI·CO만 쓰는 회사에서 매출원가에 PA를 입히는 방법을 질의한 QnA 정리다.",
    configs: ["co-margin", "xmod-obyc"],
    terms: ["profitability-analysis"],
  },
  {
    id: "sk-tablemap-735",
    category: "MM·SD 연계",
    date: "20X3.02",
    title: "SD MM PP 테이블 관계도 참고자료",
    source: "blog",
    url: "https://hksap.tistory.com/735",
    comment: "SD·MM·PP 테이블 관계도 참고자료다. 모듈 간 데이터 흐름을 파악할 때 쓰는 메모다.",
    configs: [],
    terms: ["sd-module", "mm-module"],
  },
  {
    id: "sk-mvtype-obyc-514",
    category: "MM·SD 연계",
    date: "20X4.07",
    title: "이동유형 OBYC 관련",
    source: "blog",
    url: "https://hksap.tistory.com/514",
    comment: "재고 전기(BSX)와 상계 전기(GBB) 등 이동유형별 OBYC 트랜잭션을 정리한 영문 참고자료다.",
    configs: ["xmod-obyc"],
    terms: ["obyc", "movement-type-grouping"],
  },
  {
    id: "sk-purchase-acct-515",
    category: "MM·SD 연계",
    date: "20X4.07",
    title: "Purchase account 관련",
    source: "blog",
    url: "https://hksap.tistory.com/515",
    comment: "구매계정 처리 예시를 정리한 영문 참고자료다. 구매오더 가격과 수량 기준으로 입고 시 분개가 어떻게 되는지 담겼다.",
    configs: ["xmod-obyc"],
    terms: ["obyc", "gbb"],
  },
  {
    id: "sk-grir-settle-461",
    category: "MM·SD 연계",
    date: "20X3.06",
    title: "GRIR 정산",
    source: "blog",
    url: "https://hksap.tistory.com/461",
    comment: "GR/IR 정산 때 MB5S로 입고·송장 미결 내역을 수량·금액별로 확인하는 방법을 정리한 글이다. 월말에 잔액이 남지 않도록 관리하는 실무 팁이 담겼다.",
    configs: ["close-grir"],
    terms: ["gr-ir"],
  },  {
    id: "sk-cds-inv-723",
    category: "MM·SD 연계",
    date: "20X3.01",
    title: "CDS뷰로 재고수불부 조회",
    source: "blog",
    url: "https://hksap.tistory.com/723",
    comment: "CDS 뷰로 재고수불부를 조회하는 방법을 정리한 글이다.",
    configs: [],
    terms: ["inventory-accounting", "mm-module"],
  },
  {
    id: "sk-drc-842",
    category: "회계 일반",
    date: "20X4.07",
    title: "SAP DRC관련",
    source: "blog",
    url: "https://hksap.tistory.com/842",
    comment: "SAP DRC 세무 솔루션의 확인된 기능을 정리한 글이다. 부가세 세금계산서 발행과 홈택스 신고 파일 생성, 원천세 영수증 출력을 다룬다.",
    configs: ["tax-code", "tax-procedure"],
    terms: ["tax-code"],
  },
  {
    id: "sk-ar-mgmt-449",
    category: "회계 일반",
    date: "20X3.05",
    title: "채권관리",
    source: "blog",
    url: "https://hksap.tistory.com/449",
    comment: "Residual 방식으로 반제했을 때 채권·선수금·채무·선급금 수불부를 어떻게 볼지 고민한 글이다. 원채권의 발생 정보와 정산 내역을 같은 형식으로 보고 싶다는 현업 요구가 담겼다.",
    configs: ["ar-recon"],
    terms: ["residual-item", "clearing"],
  },  {
    id: "sk-ifrs16-653",
    category: "회계 일반",
    date: "20X1.08",
    title: "IFRS16 리스회계관련 자료",
    source: "blog",
    url: "https://hksap.tistory.com/653",
    comment: "IFRS 16 리스회계 SAP 솔루션 참고자료 모음이다. 리스부채 재분류와 분개 예시가 담겼다.",
    configs: [],
    terms: ["lease-accounting", "right-of-use-asset"],
  },
  {
    id: "sk-closing-cockpit-524",
    category: "결산·마감",
    date: "20X4.08",
    title: "Closing cockpit",
    source: "blog",
    url: "https://hksap.tistory.com/524",
    comment: "사이트에 Closing Cockpit을 적용하면서 확인한 부분을 정리한 글이다. CLOCOC에서 월결산 템플릿을 만들고 릴리즈한 뒤 CLOCO에서 Task list를 불러다 결산 절차를 진행하는 기본 흐름이 담겼다.",
    configs: ["close-cockpit"],
    terms: ["closing-cockpit"],
  },
  {
    id: "sk-fxreval-test-209",
    category: "결산·마감",
    date: "20X7.09",
    title: "SAP에서 환평가 (환산손익, 환차손익, 월결산, 연결산) 테스트",
    source: "blog",
    url: "https://hksap.tistory.com/209",
    comment: "외화평가 이슈로 ECC 패치를 적용했다가 ABAP 런타임 에러가 나 고생한 기록이다. 패치 전에는 익월 1일 역분개되는 월결산 방식(without update)으로만 평가가 됐다는 내용이 담겼다.",
    configs: ["close-fxval"],
    terms: ["foreign-currency-valuation"],
  },
  {
    id: "sk-fxrate-exit-558",
    category: "결산·마감",
    date: "20X5.07",
    title: "기준환율 점검 exit",
    source: "blog",
    url: "https://hksap.tistory.com/558",
    comment: "GGB4 validation exit으로 기준환율을 점검한 사례다. 월초 1영업일에 나오는 기준환율이 없으면 전기할 때 Finance 팀에 연락하라는 메시지를 띄우도록 했다는 현장 기록이다.",
    configs: ["gl-validation"],
    terms: ["foreign-currency-valuation", "validation"],
  },
  {
    id: "sk-fcv-diff-537",
    category: "결산·마감",
    date: "20X5.03",
    title: "FAGL_FCV 평가차이 조회",
    source: "blog",
    url: "https://hksap.tistory.com/537",
    comment: "FAGL_FCV로 연평가한 내역을 FBL1N·FBL5N에서 조회하는 방법을 정리한 글이다. BSEG-BDIFF가 아니라 평가차이 필드로 봐야 한다는 실무 팁이 담겼다.",
    configs: ["close-fxval"],
    terms: ["foreign-currency-valuation"],
  },
  {
    id: "sk-mfg-cost-525",
    category: "결산·마감",
    date: "20X4.08",
    title: "제조원가명세서 관련",
    source: "blog",
    url: "https://hksap.tistory.com/525",
    comment: "제조원가명세서를 FI에서 만들기로 하고 CO 컨설턴트 도움을 받아 진행한 기록이다. 기초재료(GL)+당기매입액(GL)-타계정-매출원가(GL)로 재료비를 구하고 표준원가 투입분으로 검증하는 방식이 담겼다.",
    configs: ["close-cockpit"],
    terms: ["closing-cockpit", "production-costing"],
  },
  {
    id: "sk-purch-int-490",
    category: "MM·SD 연계",
    date: "20X4.02",
    title: "매입통합시스템 적용관련",
    source: "blog",
    url: "https://hksap.tistory.com/490",
    comment: "국세청 전자세금계산서 매입내역을 스크래핑해 쓰는 매입통합시스템 도입 시 유의점을 정리한 글이다. LIV(MIRO)를 쓰는 사이트는 한 사업자의 매입거래와 미지급거래를 MM·FI에서 나눠 처리할 프로세스 검토가 필요하다는 내용이 담겼다.",
    configs: ["tax-code"],
    terms: ["tax-code", "invoice-verification"],
  },
  {
    id: "sk-liv-tax-446",
    category: "MM·SD 연계",
    date: "20X3.05",
    title: "LIV Miro tax code",
    source: "blog",
    url: "https://hksap.tistory.com/446",
    comment: "LIV로 MIRO 처리할 때 FI에서 설정한 세금코드가 보이지 않던 현상의 점검 포인트를 정리한 글이다. IMG의 수취송장 설정 경로를 확인하는 트러블슈팅 메모다.",
    configs: ["tax-code"],
    terms: ["tax-code", "invoice-verification"],
  },
  {
    id: "sk-bset-413",
    category: "MM·SD 연계",
    date: "20X1.06",
    title: "BSET",
    source: "blog",
    url: "https://hksap.tistory.com/413",
    comment: "포워더가 통관비용을 대납하고 청구를 안 할 때 부가세 처리를 고민한 기록이다. 세관장이 본사로 세금계산서를 발행해서 부가세대급금과 잡이익으로 처리하면 BSET 테이블에 신고정보가 안 들어가는 딜레마가 담겼다.",
    configs: ["tax-code"],
    terms: ["tax-code"],
  },
  {
    id: "sk-coding-block-699",
    category: "결산·마감",
    date: "20X2.11",
    title: "총계테이블/뷰(FAGLFLEXT, ACDOCT)에 Coding Block 필드 추가방법 문의",
    source: "blog",
    url: "https://hksap.tistory.com/699",
    comment: "S/4HANA에서 총계테이블/뷰(FAGLFLEXT, ACDOCT)에 코딩블록 사용자 필드를 넣는 방법을 카페 Q&A에 문의한 글이다. ACDOCA에는 잘 들어갔는데 총계테이블은 예전 ECC처럼 IMG로 안 되고 CDS 뷰를 만들어야 하는지 묻고 있다.",
    configs: [],
    terms: ["general-ledger"],
  },
  {
    id: "sk-acdoct-report-810",
    category: "결산·마감",
    date: "20X3.11",
    title: "ACDOCT 리포트페인터 관련",
    source: "blog",
    url: "https://hksap.tistory.com/810",
    comment: "ACDOCT 테이블에 Report Painter를 쓰지 말아야 하는 이유를 정리한 참고자료를 소개한 글이다. S/4 프로젝트에서 분석팀과 리포팅을 맞추며 겪은 경험을 담은 외부 글을 링크했다.",
    configs: [],
    terms: ["general-ledger"],
  },
];