// 현장 스케치 데이터 — 계속 추가하면서 고도화
const SKETCHES = [
  {
    id: "sk-wip-mig",
    title: "시스템 신규 오픈 시 재공품 잔액 Mig 방법",
    source: "blog",
    url: "https://hksap.tistory.com/849",
    comment: "새 시스템 오픈 때 재공품 잔액을 어떻게 옮기느냐는 제조업 FI/CO의 단골 난제다. 방법론이 정해져 있지 않으면 오픈 직전까지도 논쟁이 이어지는 주제라, 미리 정리해 둔 글이 현장에서 바로 써먹힌다.",
    configs: ["co-ml"],
    terms: ["actual-costing", "material-ledger", "wip-accounting"],
  },
  {
    id: "sk-wip-provision",
    title: "재공품 미실현원가 충당금 관련",
    source: "blog",
    url: "https://hksap.tistory.com/847",
    comment: "재공품에 대한 미실현원가 충당금을 잡아야 하는지, 잡는다면 어느 시점에 잡는지 — 결산 때마다 회계팀과 실랑이하는 주제다. 기준을 정리해 둔 글이 실무 판단에 도움이 된다.",
    configs: ["co-ml"],
    terms: ["actual-costing", "wip-accounting"],
  },
  {
    id: "sk-ml-closing-alloc",
    title: "자재원장 결산 후 배부하지 않음과 배부되지 않음 관련",
    source: "blog",
    url: "https://hksap.tistory.com/845",
    comment: "자재원장 결산에서 '배부하지 않음'과 '배부되지 않음'은 비슷해 보이지만 원인과 대응이 완전히 다르다. 마감 날 밤에 마주치면 당황하기 쉬운 메시지라 정리 가치가 크다.",
    configs: ["co-alloc", "co-ml"],
    terms: ["actual-costing", "material-ledger-closing"],
  },
  {
    id: "sk-profit-center-segment",
    title: "손익센터와 세그먼트 부분",
    source: "blog",
    url: "https://hksap.tistory.com/844",
    comment: "손익센터와 세그먼트는 비슷해 보이지만 용도가 다르다. 전표분할과 함께 이해해야 하는 개념이라 FI 결산 담당자라면 한 번쯤 정리하고 넘어갈 주제다.",
    configs: ["co-prctr", "gl-docsplit"],
    terms: ["document-splitting", "profit-center"],
  },
  {
    id: "sk-real-cost-object",
    title: "Real Cost Object 관련",
    source: "blog",
    url: "https://hksap.tistory.com/839",
    comment: "실제원가를 계산할 때 기준이 되는 '실원가 대상' 개념. 말은 쉬운데 막상 시스템에서 어디에 매핑되는지 헷갈리는 경우가 많아 정리해 둘 만하다.",
    configs: ["co-ml"],
    terms: ["actual-costing"],
  },
  {
    id: "sk-cost-component",
    title: "원가구성요소 관련",
    source: "blog",
    url: "https://hksap.tistory.com/832",
    comment: "제품원가를 재료비·노무비·경비로 나누는 원가구성요소. 원가 담당자와 대화할 때 기본이 되는 개념이라 FI 쪽에서도 알아 두면 좋다.",
    configs: ["co-costvar"],
    terms: ["multilevel-costing", "production-costing"],
  },
  {
    id: "sk-copa-topdown",
    title: "CO-PA 탑다운 배부 관련 자료",
    source: "blog",
    url: "https://hksap.tistory.com/825",
    comment: "CO-PA에서 위에서 아래로 배부하는 탑다운 배부. 수익성분석을 쓰는 현장에서 결산 때마다 돌리는 로직이라 흐름을 알아 두면 좋다.",
    configs: ["co-alloc", "co-margin"],
    terms: ["allocation", "profitability-analysis"],
  },
  {
    id: "sk-internal-order-public",
    title: "S/4HANA Cloud Public edition Internal Order관련",
    source: "blog",
    url: "https://hksap.tistory.com/814",
    comment: "Public Edition에서 내부오더가 어떻게 동작하는지 정리한 글. Public은 CO 설정이 제한적이라 되는 것과 안 되는 것을 구분해 두는 게 중요하다.",
    configs: ["co-order"],
    terms: ["internal-order"],
  },
  {
    id: "sk-material-ledger-actual",
    title: "Material Ledgers/ Actual Costing 관련",
    source: "blog",
    url: "https://hksap.tistory.com/812",
    comment: "자재원장과 실제원가계산의 관계를 정리한 글. 표준원가와 실제원가의 차이가 어디서 발생하는지 이해하는 출발점이다.",
    configs: ["co-ml", "xmod-ml"],
    terms: ["actual-costing", "material-ledger"],
  },
  {
    id: "sk-ml-table",
    title: "ML Table 관련",
    source: "blog",
    url: "https://hksap.tistory.com/773",
    comment: "자재원장 뒤에 있는 테이블들 정리. 장애나 마감 이슈 때 테이블을 직접 뒤져야 하는 순간이 오는데, 그때 어디를 봐야 하는지 아는 것과 모르는 것의 차이가 크다.",
    configs: ["xmod-ml"],
    terms: ["material-ledger"],
  },
  {
    id: "sk-miro-split",
    title: "MIRO 송장처리 시 FI전표 분할 관련",
    source: "blog",
    url: "https://hksap.tistory.com/727",
    comment: "MIRO로 송장을 처리할 때 FI 전표가 분할되는 케이스. MM과 FI 경계에서 생기는 이슈라 양쪽 지식이 함께 필요하다.",
    configs: ["close-grir", "gl-docsplit"],
    terms: ["document-splitting", "invoice-verification"],
  },
  {
    id: "sk-reversal-test",
    title: "역분개전표 역분개 테스트관련",
    source: "blog",
    url: "https://hksap.tistory.com/784",
    comment: "역분개한 전표를 다시 역분개하는 테스트. 말장난 같지만 결산 조정에서 실제로 마주치는 상황이라, 동작 방식을 미리 확인해 두면 실수를 줄일 수 있다.",
    configs: ["gl-reversal-reason"],
    terms: ["reversal"],
  },
  {
    id: "sk-offbook-assets",
    title: "장부외자산 1천여 건 생성 및 역분개 처리",
    source: "facebook",
    url: "",
    comment: "장부에 없던 자산 1천여 건을 한 번에 생성하고 역분개까지 처리한 현장 기록. 대량 데이터 처리에서 번호·일자·역분개 사유를 어떻게 통제하는지 보여주는 사례다.",
    configs: ["aa-class", "gl-reversal-reason"],
    terms: ["reversal"],
  },
  {
    id: "sk-card-dup",
    title: "법인카드 경비 전표 중복 생성 — 락 오브젝트 통과 사례",
    source: "facebook",
    url: "",
    comment: "법인카드 경비 전표를 두 번 눌러 중복 생성된 사건. 락 오브젝트를 통과해 들어온 케이스로, 인터페이스 전표에서 중복 방지가 왜 중요한지 보여준다.",
    configs: ["gl-doc-type"],
    terms: ["document"],
  },
  {
    id: "sk-wip-actual-public",
    title: "WIP at Actual — Public에서 전표 나온 날",
    source: "facebook",
    url: "",
    comment: "Public Edition에서 WIP at Actual로 전표가 처음 나온 날의 기록. Public에서 CO가 돌아간다는 것 자체가 관심사라 현장감이 있다.",
    configs: ["co-ml"],
    terms: ["actual-costing", "wip-accounting"],
  },
  {
    id: "sk-co-settle-mismatch",
    title: "CO 결산 검증 — 타계정이 원계정 안 따라감",
    source: "facebook",
    url: "",
    comment: "CO 결산 검증 중 타계정이 원계정을 따라가지 않은 이슈. 배부·분배 로직에서 계정 매핑이 어긋나면 생기는 전형적인 결산 트러블이다.",
    configs: ["co-alloc", "co-close"],
    terms: ["allocation"],
  },
  {
    id: "sk-first-close",
    title: "오픈 후 첫 결산 드디어 끝",
    source: "facebook",
    url: "",
    comment: "시스템 오픈 후 첫 결산을 마친 날의 기록. 오픈 첫 달 결산이 왜 힘든지 겪어본 사람만 아는 감정이 담겨 있다.",
    configs: ["close-cockpit"],
    terms: ["closing-cockpit"],
  },
  {
    id: "sk-gl-ml-mismatch",
    title: "FI G/L 잔액 vs CO-ML 금액 불일치 — OSS 재등록",
    source: "evernote",
    url: "",
    comment: "운영 시스템에서 FI G/L 잔액과 CO 자재원장 금액이 맞지 않아 OSS에 재등록 요청한 사례. FI와 CO가 어긋나는 순간이 왜 생기는지 보여주는 트러블슈팅 기록이다.",
    configs: ["co-ml", "xmod-ml"],
    terms: ["actual-costing", "material-ledger"],
  },
  {
    id: "sk-overseas-go-live-close",
    title: "해외법인 오픈 후 첫 월결산 — FI/CO 일치로 마감",
    source: "evernote",
    url: "",
    comment: "해외법인 오픈 후 8월 결산을 물류 D+2, 재무/원가 D+6에 FI/CO 일치로 마친 기록. 결산 스케줄이 현장에서 어떻게 돌아가는지 보여주는 사례다.",
    configs: ["close-cockpit"],
    terms: ["closing-cockpit"],
  },
  {
    id: "sk-lines-999",
    title: "999라인 넘는 전표",
    source: "keep",
    url: "",
    comment: "한 전표에 999라인이 넘는 경우에 대한 메모. 대량 라인 전표는 성능·번호·출력에서 별도 고려가 필요해 현장에서 자주話題가 된다.",
    configs: ["gl-doc-type"],
    terms: ["document", "line-item"],
  },
];
